"""
Local, curated knowledge base for diseases and common medicines.
This is the offline fallback / first line of the chatbot (fast, reliable,
no network dependency) and is what powers the Disease Profiles section.
Live medicine search (any drug name) is handled separately by openfda_client.py.
"""

# Common drug abbreviations, slang, and brand aliases → resolved name
DRUG_ALIASES = {
    "ctz": "cetirizine",
    "avil": "pheniramine",
    "crocin": "paracetamol",
    "dolo": "paracetamol",
    "tylenol": "paracetamol",
    "calpol": "paracetamol",
    "advil": "ibuprofen",
    "motrin": "ibuprofen",
    "brufen": "ibuprofen",
    "combiflam": "ibuprofen + paracetamol",
    "zyrtec": "cetirizine",
    "cetrine": "cetirizine",
    "alerid": "cetirizine",
    "allegra": "fexofenadine",
    "benadryl": "diphenhydramine",
    "phenergan": "promethazine",
    "volini": "diclofenac",
    "voveran": "diclofenac",
    "diclo": "diclofenac",
    "gelusil": "antacid",
    "pan": "pantoprazole",
    "pantop": "pantoprazole",
    "omez": "omeprazole",
    "omeza": "omeprazole",
    "azee": "azithromycin",
    "zifi": "cifixime",
    "cif": "cifixime",
    "augmentin": "amoxicillin + clavulanate",
    "amox": "amoxicillin",
    "met": "metformin",
    "glycomet": "metformin",
    "glucophage": "metformin",
    "telma": "telmisartan",
    "amlo": "amlodipine",
    "amlodac": "amlodipine",
    "atorva": "atorvastatin",
    "rosuvas": "rosuvastatin",
    "clopitab": "clopidogrel",
    "ecosprin": "aspirin",
    "aspirin": "aspirin",
    "ecotrin": "aspirin",
    "sinarest": "paracetamol + phenylephrine + chlorpheniramine",
    "vicks": "dextromethorphan",
    "benedryl": "diphenhydramine",
    "dramamine": "dimenhydrinate",
    "avomine": "promethazine",
    "stugil": "ondansetron",
    "ondem": "ondansetron",
    "ondansetron": "ondansetron",
    "panadol": "paracetamol",
    "tylenol": "paracetamol",
    "febrectol": "paracetamol",
    "meftal": "mefenamic acid",
    "meftal-spas": "mefenamic acid + dicyclomine",
    "dicyclomine": "dicyclomine",
    "buscopan": "hyoscine butylbromide",
    "ranitidine": "ranitidine",
    "zantac": "ranitidine",
    "pantodac": "pantoprazole",
    "razo": "pantoprazole",
    "lanzol": "lansoprazole",
    "lans": "lansoprazole",
    "ventolin": "salbutamol",
    "asthalin": "salbutamol",
    "duolin": "ipratropium + salbutamol",
    "deriphyllin": "theophylline",
    "theo": "theophylline",
    "levocet": "levocetirizine",
    "lcet": "levocetirizine",
    "aloquin": "hydroxychloroquine",
    "hcqs": "hydroxychloroquine",
    "chloroquine": "chloroquine",
    "doxycycline": "doxycycline",
    "doxy": "doxycycline",
    "metro": "metronidazole",
    "metronidazole": "metronidazole",
    "flagyl": "metronidazole",
    "nidazol": "metronidazole",
    "taxim": "ceftriaxone",
    "cef": "ceftriaxone",
    "ceftriaxone": "ceftriaxone",
    "monocef": "ceftriaxone",
    "panacea": "paracetamol",
    "ibugesic": "ibuprofen",
    "nise": "nimesulide",
    "nimesulide": "nimesulide",
    "nicide": "nimesulide",
    "tramadol": "tramadol",
    "ultram": "tramadol",
    "ultracet": "tramadol + paracetamol",
    "codeine": "codeine",
    "cofidox": "codeine",
    "morphine": "morphine",
    "hydrocodone": "hydrocodone",
    "oxycodone": "oxycodone",
    "percocet": "oxycodone + acetaminophen",
    "vicodin": "hydrocodone + acetaminophen",
    "diabet": "diabetes",
    "bp": "hypertension",
    "sugar": "diabetes",
    "tension": "hypertension",
    "cholesterol": "hyperlipidemia",
    "thyroid": "hypothyroidism",
    "sugar tablets": "metformin",
    "bp tablet": "amlodipine",
    "sugar tablet": "metformin",
    "cholesterol tablet": "atorvastatin",
    "cipro": "ciprofloxacin",
    "ciplox": "ciprofloxacin",
    "ciproxin": "ciprofloxacin",
    "amlodac": "amlodipine",
    "amlokind": "amlodipine",
    "atorvast": "atorvastatin",
    "lipitor": "atorvastatin",
    "stator": "atorvastatin",
    "losartan": "losartan",
    "losar": "losartan",
    "cozaar": "losartan",
    "montair": "montelukast",
    "montelukast": "montelukast",
    "singulair": "montelukast",
    "ranitidine": "ranitidine",
    "zantac": "ranitidine",
    "naproxen": "naproxen",
    "naprosyn": "naproxen",
    "aleve": "naproxen",
    "sertraline": "sertraline",
    "zoloft": "sertraline",
    "serta": "sertraline",
    "escitalopram": "escitalopram",
    "lexapro": "escitalopram",
    "cipralex": "escitalopram",
    "esita": "escitalopram",
    "metoprolol": "metoprolol",
    "lopressor": "metoprolol",
    "toprol": "metoprolol",
    "lozak": "losartan",
    "telmisartan": "telmisartan",
    "micardis": "telmisartan",
    "bisoprolol": "bisoprolol",
    "concor": "bisoprolol",
    "warfarin": "warfarin",
    "coumadin": "warfarin",
    "heparin": "heparin",
    "clopidogrel": "clopidogrel",
    "plavix": "clopidogrel",
    "gabapentin": "gabapentin",
    "neurontin": "gabapentin",
    "pregabalin": "pregabalin",
    "lyrica": "pregabalin",
    "prednisolone": "prednisolone",
    "prednisone": "prednisone",
    "dexamethasone": "dexamethasone",
    "dexona": "dexamethasone",
    "montek": "montelukast",
    "doxycycline": "doxycycline",
    "doxy": "doxycycline",
    "vibramycin": "doxycycline",
    "ciprofloxacin": "ciprofloxacin",
    "levofloxacin": "levofloxacin",
    "levoquin": "levofloxacin",
    "omeprazole": "omeprazole",
    "prilosec": "omeprazole",
    "lansoprazole": "lansoprazole",
    "prevacid": "lansoprazole",
    "ondansetron": "ondansetron",
    "zofran": "ondansetron",
    "paracetamol": "paracetamol",
    "acetaminophen": "paracetamol",
    "ibuprofen": "ibuprofen",
    "diclofenac": "diclofenac",
    "cetirizine": "cetirizine",
    "amoxicillin": "amoxicillin",
    "metformin": "metformin",
    "azithromycin": "azithromycin",
    "salbutamol": "salbutamol",
    "levothyroxine": "levothyroxine",
    "nimesulide": "nimesulide",
    "metronidazole": "metronidazole",
    "pantoprazole": "pantoprazole",
    "pheniramine": "pheniramine",
    "loratadine": "loratadine",
    "fexofenadine": "fexofenadine",
    "diphenhydramine": "diphenhydramine",
    "promethazine": "promethazine",
    "aspirin": "aspirin",
    "tramadol": "tramadol",
    "codeine": "codeine",
    "morphine": "morphine",
}

DISEASE_KNOWLEDGE = {
    "diabetes": {
        "category": "Endocrine",
        "symptoms": ["Frequent urination", "Excessive thirst", "Extreme hunger", "Unexplained weight loss", "Fatigue", "Blurred vision", "Slow-healing sores", "Tingling in hands/feet"],
        "causes": ["Genetics", "Obesity", "Lack of physical activity", "Insulin resistance", "Autoimmune condition (Type 1)", "Pancreatic damage"],
        "treatment": ["Metformin", "Insulin therapy", "Diet control", "Regular exercise", "Blood sugar monitoring", "SGLT2 inhibitors", "GLP-1 agonists"],
        "prevention": ["Healthy diet", "Regular exercise", "Maintain healthy weight", "Regular check-ups", "Limit sugar intake"],
        "complications": ["Heart disease", "Kidney damage (nephropathy)", "Nerve damage (neuropathy)", "Eye problems (retinopathy)", "Foot problems", "Stroke"],
        "emergency_signs": ["Very high blood sugar (>300mg/dL)", "Ketones in urine", "Fruity breath odor", "Confusion", "Severe dizziness", "Loss of consciousness"],
        "when_to_see_doctor": "If experiencing persistent thirst/urination, unexplained weight loss, or blood sugar readings consistently above target range."
    },
    "hypertension": {
        "category": "Cardiovascular",
        "symptoms": ["Often asymptomatic", "Headache", "Shortness of breath", "Nosebleeds", "Flushing", "Dizziness", "Chest pain (severe cases)"],
        "causes": ["High salt diet", "Obesity", "Genetics", "Chronic stress", "Lack of exercise", "Smoking", "Excess alcohol", "Kidney disease"],
        "treatment": ["ACE inhibitors", "Calcium channel blockers", "Diuretics", "Beta-blockers", "ARBs", "Lifestyle changes"],
        "prevention": ["Reduce salt intake", "Regular exercise", "Healthy weight", "Stress management", "Limit alcohol", "Quit smoking"],
        "complications": ["Heart attack", "Stroke", "Kidney failure", "Vision loss", "Vascular dementia", "Aneurysm"],
        "emergency_signs": ["BP above 180/120 (hypertensive crisis)", "Severe headache", "Sudden vision changes", "Numbness/weakness", "Speech difficulty", "Chest pain"],
        "when_to_see_doctor": "Get BP checked regularly even without symptoms — hypertension is often silent until complications arise."
    },
    "fever": {
        "category": "General/Infectious",
        "symptoms": ["High body temperature (>38°C)", "Chills", "Sweating", "Headache", "Muscle aches", "Loss of appetite", "Fatigue", "Dehydration"],
        "causes": ["Viral infection", "Bacterial infection", "Heat exhaustion", "Inflammatory conditions", "Medication side effects", "Vaccination response"],
        "treatment": ["Paracetamol", "Ibuprofen", "Rest", "Hydration", "Cold compress", "Light clothing"],
        "prevention": ["Vaccination", "Hand washing", "Avoid close contact with sick people", "Good hygiene"],
        "complications": ["Dehydration", "Febrile seizures (children)", "Underlying infection worsening"],
        "emergency_signs": ["Very high fever (above 40°C)", "Seizures", "Stiff neck", "Difficulty breathing", "Confusion", "Persistent vomiting", "Rash"],
        "when_to_see_doctor": "If fever exceeds 39.5°C, lasts more than 3 days, or is accompanied by severe symptoms."
    },
    "common cold": {
        "category": "Respiratory",
        "symptoms": ["Runny nose", "Sneezing", "Cough", "Sore throat", "Mild headache", "Low-grade fever", "Nasal congestion", "Watery eyes"],
        "causes": ["Rhinovirus", "Coronavirus (common cold strains)", "Cold weather exposure", "Weak immune system", "Close contact with infected person"],
        "treatment": ["Rest", "Hydration", "Antihistamines", "Decongestants", "Paracetamol for fever", "Throat lozenges", "Steam inhalation"],
        "prevention": ["Hand washing", "Avoid touching face", "Vitamin C", "Warm clothing", "Avoid crowded places", "Adequate sleep"],
        "complications": ["Sinus infection", "Ear infection", "Bronchitis (rare)"],
        "emergency_signs": ["High fever", "Difficulty breathing", "Wheezing", "Chest pain", "Severe headache", "Symptoms lasting >10 days"],
        "when_to_see_doctor": "If symptoms worsen after a week or are accompanied by high fever or breathing difficulty."
    },
    "influenza": {
        "category": "Respiratory",
        "symptoms": ["Sudden high fever", "Severe body aches", "Dry cough", "Extreme fatigue", "Headache", "Sore throat", "Chills"],
        "causes": ["Influenza A/B virus", "Seasonal transmission", "Close contact with infected individuals"],
        "treatment": ["Rest", "Fluids", "Antivirals (oseltamivir) if started early", "Paracetamol", "Symptomatic relief"],
        "prevention": ["Annual flu vaccine", "Hand hygiene", "Avoid crowded indoor spaces during flu season"],
        "complications": ["Pneumonia", "Bronchitis", "Worsening of chronic conditions", "Hospitalization in high-risk groups"],
        "emergency_signs": ["Difficulty breathing", "Persistent chest pain", "Severe dehydration", "Bluish lips/face", "Confusion"],
        "when_to_see_doctor": "High-risk individuals (elderly, pregnant, chronic illness) should seek care early; others if symptoms are severe or worsening."
    },
    "asthma": {
        "category": "Respiratory",
        "symptoms": ["Wheezing", "Shortness of breath", "Chest tightness", "Coughing (especially at night)", "Difficulty exercising"],
        "causes": ["Allergens (dust, pollen, pet dander)", "Genetics", "Air pollution", "Respiratory infections", "Cold air", "Exercise"],
        "treatment": ["Inhaled bronchodilators (Salbutamol)", "Inhaled corticosteroids", "Leukotriene modifiers", "Avoiding triggers"],
        "prevention": ["Identify and avoid triggers", "Use air purifiers", "Regular use of preventer inhalers", "Flu vaccination"],
        "complications": ["Severe asthma attacks", "Reduced lung function over time", "Sleep disturbance"],
        "emergency_signs": ["Severe breathlessness", "Inability to speak full sentences", "Bluish lips", "No relief from rescue inhaler"],
        "when_to_see_doctor": "If using rescue inhaler more than twice a week or experiencing nighttime symptoms regularly."
    },
    "migraine": {
        "category": "Neurological",
        "symptoms": ["Throbbing head pain (often one-sided)", "Nausea", "Vomiting", "Sensitivity to light and sound", "Visual aura", "Dizziness"],
        "causes": ["Genetics", "Hormonal changes", "Stress", "Certain foods/additives", "Sleep changes", "Sensory stimuli"],
        "treatment": ["Triptans", "NSAIDs", "Anti-nausea medication", "Preventive medications (beta-blockers, anticonvulsants)", "Rest in dark room"],
        "prevention": ["Identify and avoid triggers", "Regular sleep schedule", "Stress management", "Stay hydrated", "Limit caffeine"],
        "complications": ["Chronic migraine", "Medication overuse headache", "Status migrainosus"],
        "emergency_signs": ["Sudden 'worst-ever' headache", "Headache with fever and stiff neck", "Headache after head injury", "Weakness or vision loss"],
        "when_to_see_doctor": "If migraines are frequent, worsening, or not responding to standard treatment."
    },
    "headache": {
        "category": "Neurological",
        "symptoms": ["Head pain", "Sensitivity to light", "Nausea", "Difficulty concentrating", "Neck stiffness"],
        "causes": ["Stress", "Dehydration", "Eye strain", "Sinus issues", "Tension", "Poor posture", "Lack of sleep"],
        "treatment": ["Ibuprofen", "Paracetamol", "Rest", "Hydration", "Cold compress", "Dark quiet room"],
        "prevention": ["Stay hydrated", "Regular sleep", "Stress management", "Eye breaks from screens", "Good posture"],
        "complications": ["Chronic daily headache", "Medication overuse headache"],
        "emergency_signs": ["Sudden severe headache", "Headache with fever", "Headache with confusion", "Loss of consciousness", "Worst headache of life"],
        "when_to_see_doctor": "If headaches are frequent, severe, or accompanied by neurological symptoms."
    },
    "gastroenteritis": {
        "category": "Digestive",
        "symptoms": ["Diarrhea", "Vomiting", "Abdominal cramps", "Nausea", "Low-grade fever", "Dehydration"],
        "causes": ["Viral infection (norovirus, rotavirus)", "Bacterial infection (Salmonella, E. coli)", "Contaminated food/water", "Parasites"],
        "treatment": ["Oral rehydration solution", "Rest", "Bland diet (BRAT)", "Antiemetics if needed", "Probiotics"],
        "prevention": ["Hand washing", "Safe food handling", "Clean drinking water", "Proper food storage"],
        "complications": ["Severe dehydration", "Electrolyte imbalance", "Kidney injury (severe cases)"],
        "emergency_signs": ["Signs of severe dehydration", "Blood in stool/vomit", "High fever", "Persistent vomiting unable to keep fluids down"],
        "when_to_see_doctor": "If symptoms last more than 2-3 days, or there are signs of dehydration or blood in stool."
    },
    "gerd": {
        "category": "Digestive",
        "symptoms": ["Heartburn", "Acid regurgitation", "Chest discomfort", "Difficulty swallowing", "Chronic cough", "Bloating"],
        "causes": ["Weak lower esophageal sphincter", "Obesity", "Spicy/fatty food", "Smoking", "Pregnancy", "Hiatal hernia"],
        "treatment": ["Proton pump inhibitors (Omeprazole)", "H2 blockers", "Antacids", "Dietary changes", "Weight loss"],
        "prevention": ["Avoid trigger foods", "Eat smaller meals", "Don't lie down right after eating", "Maintain healthy weight"],
        "complications": ["Esophagitis", "Esophageal stricture", "Barrett's esophagus"],
        "emergency_signs": ["Severe chest pain", "Difficulty swallowing solids", "Vomiting blood", "Black stools"],
        "when_to_see_doctor": "If symptoms occur more than twice a week or over-the-counter remedies aren't helping."
    },
    "insomnia": {
        "category": "Sleep/Mental Health",
        "symptoms": ["Difficulty falling asleep", "Waking up during night", "Early morning awakening", "Daytime fatigue", "Irritability", "Poor concentration"],
        "causes": ["Stress", "Poor sleep habits", "Caffeine", "Alcohol", "Medical conditions", "Medications", "Anxiety/depression"],
        "treatment": ["Improved sleep hygiene", "Relaxation techniques", "Melatonin", "Cognitive behavioral therapy (CBT-I)", "Short-term sleep aids (doctor-guided)"],
        "prevention": ["Regular sleep schedule", "Avoid caffeine before bed", "Limit screen time", "Relaxing bedtime routine", "Comfortable sleep environment"],
        "complications": ["Chronic fatigue", "Worsened mental health", "Reduced immune function"],
        "emergency_signs": ["Severe anxiety", "Depression with hopelessness", "Suicidal thoughts"],
        "when_to_see_doctor": "If insomnia persists for more than a few weeks and affects daily functioning."
    },
    "anxiety disorder": {
        "category": "Mental Health",
        "symptoms": ["Excessive worry", "Restlessness", "Fatigue", "Difficulty concentrating", "Irritability", "Rapid heartbeat", "Muscle tension"],
        "causes": ["Genetics", "Brain chemistry", "Chronic stress", "Trauma", "Medical conditions", "Substance use"],
        "treatment": ["Cognitive behavioral therapy", "Exercise", "Deep breathing/relaxation", "Medications (SSRIs, SNRIs)", "Mindfulness practices"],
        "prevention": ["Regular exercise", "Stress management", "Healthy diet", "Social support", "Limit caffeine/alcohol"],
        "complications": ["Panic disorder", "Social isolation", "Substance misuse", "Depression"],
        "emergency_signs": ["Panic attacks with chest pain", "Shortness of breath", "Suicidal thoughts", "Inability to function"],
        "when_to_see_doctor": "If anxiety interferes significantly with daily life or relationships."
    },
    "depression": {
        "category": "Mental Health",
        "symptoms": ["Persistent sadness", "Loss of interest in activities", "Fatigue", "Sleep changes", "Appetite changes", "Difficulty concentrating", "Feelings of hopelessness", "Low self-worth"],
        "causes": ["Genetics", "Brain chemistry imbalance", "Trauma", "Chronic stress", "Medical conditions", "Major life events", "Social isolation"],
        "treatment": ["Psychotherapy (CBT, talk therapy)", "Exercise", "Social support", "Antidepressants (under medical supervision)", "Lifestyle changes"],
        "prevention": ["Healthy relationships", "Regular exercise", "Stress management", "Early professional help", "Adequate sleep"],
        "complications": ["Suicidal ideation", "Substance abuse", "Social withdrawal", "Physical health decline"],
        "emergency_signs": ["Suicidal thoughts or plans", "Self-harm", "Not eating for extended periods", "Severe withdrawal from others"],
        "when_to_see_doctor": "Please reach out to a mental health professional if persistent sadness or hopelessness lasts more than two weeks."
    },
    "urinary tract infection": {
        "category": "Urological",
        "symptoms": ["Burning sensation while urinating", "Frequent urge to urinate", "Cloudy urine", "Pelvic pain", "Strong-smelling urine", "Low-grade fever"],
        "causes": ["Bacterial infection (commonly E. coli)", "Poor hygiene", "Holding urine too long", "Sexual activity", "Catheter use"],
        "treatment": ["Antibiotics (Nitrofurantoin, Trimethoprim)", "Increased water intake", "Pain relief (Phenazopyridine)", "Cranberry products (supportive)"],
        "prevention": ["Stay hydrated", "Urinate after intercourse", "Proper hygiene", "Avoid holding urine"],
        "complications": ["Kidney infection (pyelonephritis)", "Recurrent UTIs", "Sepsis (rare, severe cases)"],
        "emergency_signs": ["High fever with chills", "Severe back/flank pain", "Blood in urine", "Confusion (especially elderly)"],
        "when_to_see_doctor": "At first signs of UTI symptoms, especially if fever or back pain develops."
    },
    "allergic rhinitis": {
        "category": "Allergic/Immune",
        "symptoms": ["Sneezing", "Runny/itchy nose", "Itchy watery eyes", "Nasal congestion", "Postnasal drip"],
        "causes": ["Pollen", "Dust mites", "Pet dander", "Mold", "Seasonal allergens"],
        "treatment": ["Antihistamines (Cetirizine, Loratadine)", "Nasal corticosteroid sprays", "Decongestants", "Allergen avoidance", "Immunotherapy"],
        "prevention": ["Avoid known allergens", "Use air purifiers", "Keep windows closed during high pollen", "Regular cleaning"],
        "complications": ["Sinusitis", "Sleep disruption", "Worsened asthma"],
        "emergency_signs": ["Difficulty breathing", "Swelling of face/throat (anaphylaxis)", "Severe wheezing"],
        "when_to_see_doctor": "If symptoms are persistent year-round or significantly affect quality of life."
    },
    "anemia": {
        "category": "Hematological",
        "symptoms": ["Fatigue", "Pale skin", "Shortness of breath", "Dizziness", "Cold hands/feet", "Rapid heartbeat", "Brittle nails"],
        "causes": ["Iron deficiency", "Vitamin B12/folate deficiency", "Chronic disease", "Blood loss", "Genetic conditions (thalassemia, sickle cell)"],
        "treatment": ["Iron supplements", "Vitamin B12/folate supplements", "Dietary changes", "Treating underlying cause", "Blood transfusion (severe cases)"],
        "prevention": ["Iron-rich diet", "Vitamin C with iron-rich meals", "Regular health screening", "Manage chronic conditions"],
        "complications": ["Heart problems", "Pregnancy complications", "Developmental delays (children)"],
        "emergency_signs": ["Severe shortness of breath", "Chest pain", "Fainting", "Very rapid heartbeat"],
        "when_to_see_doctor": "If experiencing persistent fatigue, pale skin, or breathlessness on minimal exertion."
    },
    "thyroid disorder (hypothyroidism)": {
        "category": "Endocrine",
        "symptoms": ["Fatigue", "Weight gain", "Cold intolerance", "Dry skin", "Hair loss", "Constipation", "Depression", "Muscle weakness"],
        "causes": ["Hashimoto's thyroiditis (autoimmune)", "Iodine deficiency", "Thyroid surgery/radiation", "Certain medications"],
        "treatment": ["Levothyroxine (thyroid hormone replacement)", "Regular thyroid function monitoring"],
        "prevention": ["Adequate iodine intake", "Regular screening if at risk", "Monitor during pregnancy"],
        "complications": ["Goiter", "Heart problems", "Myxedema (severe, rare)", "Infertility"],
        "emergency_signs": ["Severe lethargy", "Confusion", "Very low body temperature", "Slow heart rate with fainting"],
        "when_to_see_doctor": "If experiencing unexplained fatigue, weight changes, or cold intolerance — get thyroid levels checked."
    },
    "arthritis": {
        "category": "Musculoskeletal",
        "symptoms": ["Joint pain", "Stiffness (especially morning)", "Swelling", "Reduced range of motion", "Warmth around joint"],
        "causes": ["Age-related wear (osteoarthritis)", "Autoimmune response (rheumatoid arthritis)", "Genetics", "Joint injury", "Obesity"],
        "treatment": ["NSAIDs (Ibuprofen)", "Physical therapy", "DMARDs (for RA)", "Corticosteroid injections", "Weight management", "Joint replacement (severe cases)"],
        "prevention": ["Maintain healthy weight", "Regular low-impact exercise", "Protect joints during activity"],
        "complications": ["Joint deformity", "Reduced mobility", "Chronic pain"],
        "emergency_signs": ["Sudden severe joint swelling with fever (possible joint infection)", "Inability to move joint"],
        "when_to_see_doctor": "If joint pain persists beyond a few weeks or significantly limits daily activities."
    },
    "eczema": {
        "category": "Dermatological",
        "symptoms": ["Itchy skin", "Dry, red patches", "Cracked or scaly skin", "Small bumps that may ooze", "Skin thickening from scratching"],
        "causes": ["Genetics", "Dry skin", "Irritants (soaps, detergents)", "Allergens", "Stress", "Heat and sweat", "Immune system dysfunction"],
        "treatment": ["Moisturizers (emollients)", "Topical corticosteroids", "Antihistamines for itch relief", "Topical calcineurin inhibitors", "Avoiding triggers", "Wet wrap therapy"],
        "prevention": ["Regular moisturizing", "Avoid harsh soaps", "Wear soft cotton clothing", "Keep nails short", "Humidifier in dry environments"],
        "complications": ["Skin infections", "Sleep disruption", "Emotional distress", "Asthma (atopic march)"],
        "emergency_signs": ["Signs of skin infection (pus, fever)", "Widespread rash", "Fever with rash"],
        "when_to_see_doctor": "If OTC moisturizers and hydrocortisone don't control symptoms after 1-2 weeks."
    },
    "urticaria (hives)": {
        "category": "Dermatological/Allergic",
        "symptoms": ["Raised, red or skin-colored welts", "Intense itching", "Swelling (angioedema)", "Welts that move around the body"],
        "causes": ["Allergic reactions (food, medication, insect stings)", "Physical triggers (heat, cold, pressure)", "Infections", "Stress", "Autoimmune conditions"],
        "treatment": ["Antihistamines (Cetirizine, Loratadine)", "Avoiding known triggers", "Cold compresses", "Corticosteroids (severe cases)", "Omalizumab (chronic cases)"],
        "prevention": ["Identify and avoid triggers", "Keep a symptom diary", "Wear loose-fitting clothing"],
        "complications": ["Anaphylaxis (rare but dangerous)", "Chronic hives affecting quality of life"],
        "emergency_signs": ["Difficulty breathing", "Swelling of throat/tongue", "Dizziness or fainting", "Rapid pulse"],
        "when_to_see_doctor": "If hives last more than 6 weeks, recur frequently, or are accompanied by swelling of lips/throat."
    },
    "alzheimer's disease": {
        "category": "Neurological",
        "symptoms": ["Memory loss", "Confusion", "Difficulty with familiar tasks", "Misplacing things", "Poor judgment", "Withdrawal from social activities", "Mood and personality changes", "Difficulty finding words"],
        "causes": ["Age (most significant risk factor)", "Genetics (family history)", "Down syndrome", "Cardiovascular disease", "History of head trauma", "Low education level"],
        "treatment": ["Cholinesterase inhibitors (Donepezil, Rivastigmine, Galantamine)", "Memantine", "Lecanemab (newer anti-amyloid therapy)", "Supportive care and cognitive stimulation", "Managing behavioral symptoms"],
        "prevention": ["Regular physical exercise", "Mental stimulation", "Social engagement", "Heart-healthy diet", "Control blood pressure and diabetes", "Quality sleep"],
        "complications": ["Inability to perform daily activities", "Infections (pneumonia, UTIs)", "Falls and fractures", "Malnutrition", "Complete dependence on caregivers"],
        "emergency_signs": ["Sudden severe confusion", "Falls with head injury", "Inability to eat or drink", "Seizures", "Sudden personality change"],
        "when_to_see_doctor": "If memory problems or confusion are interfering with daily life. Early diagnosis allows for better planning and treatment."
    },
    "skin rash": {
        "category": "Dermatological",
        "symptoms": ["Red, irritated skin", "Itching", "Bumps or blisters", "Swelling", "Warmth at affected area"],
        "causes": ["Allergic reactions", "Infections (bacterial, viral, fungal)", "Autoimmune conditions", "Medication side effects", "Contact irritants", "Heat/sweat"],
        "treatment": ["Topical corticosteroids", "Antihistamines", "Antibiotics (if bacterial)", "Antifungals (if fungal)", "Moisturizers", "Avoiding triggers"],
        "prevention": ["Avoid known allergens", "Use hypoallergenic products", "Keep skin clean and moisturized", "Wear breathable fabrics"],
        "complications": ["Skin infection", "Scarring", "Post-inflammatory hyperpigmentation", "Chronic skin changes"],
        "emergency_signs": ["Rapidly spreading rash", "Rash with fever", "Rash with difficulty breathing", "Blistering or peeling skin"],
        "when_to_see_doctor": "If rash is widespread, painful, blistering, accompanied by fever, or doesn't improve with OTC treatment."
    },
    "dengue fever": {
        "category": "Infectious/Tropical",
        "symptoms": ["High fever (40°C/104°F)", "Severe headache (especially behind eyes)", "Joint and muscle pain (breakbone fever)", "Nausea and vomiting", "Skin rash (appears 2-5 days after fever)", "Fatigue", "Mild bleeding (nose, gums)", "Easy bruising"],
        "causes": ["Dengue virus (DENV 1-4)", "Transmitted by Aedes aegypti mosquito bite", "No direct person-to-person transmission"],
        "treatment": ["No specific antiviral — supportive care only", "Paracetamol for fever (AVOID aspirin/ibuprofen — bleeding risk)", "IV fluids if severely dehydrated", "Rest", "Monitoring platelet count"],
        "prevention": ["Mosquito repellent (DEET, picaridin)", "Wear long sleeves in endemic areas", "Eliminate standing water", "Use mosquito nets", "Screen windows/doors"],
        "complications": ["Dengue Hemorrhagic Fever (severe bleeding)", "Dengue Shock Syndrome (dangerous drop in blood pressure)", "Organ failure", "Death (rare but possible)"],
        "emergency_signs": ["Severe abdominal pain", "Persistent vomiting", "Bleeding from gums/nose", "Blood in vomit/stool", "Rapid drop in platelet count", "Cold clammy skin", "Restlessness"],
        "when_to_see_doctor": "Immediately if fever persists beyond 2 days, or if any emergency signs appear. Critical period is days 3-7."
    },
    "malaria": {
        "category": "Infectious/Tropical",
        "symptoms": ["Cyclical high fever with chills and rigors", "Sweating episodes", "Headache", "Nausea and vomiting", "Fatigue and body aches", "Enlarged spleen", "Mild jaundice"],
        "causes": ["Plasmodium parasite (P. falciparum, P. vivax, P. ovale, P. malariae)", "Transmitted by female Anopheles mosquito bite", "Also via blood transfusion or shared needles"],
        "treatment": ["Artemisinin-based combination therapy (ACT) for P. falciparum", "Chloroquine for P. vivax (where still effective)", "Primaquine for liver-stage P. vivax/ovale", "IV artesunate for severe malaria", "Supportive care"],
        "prevention": ["Antimalarial prophylaxis (Malarone, Doxycycline, Mefloquine) for travelers", "Mosquito nets (insecticide-treated)", "Repellent (DEET)", "Eliminate mosquito breeding sites", "Protective clothing"],
        "complications": ["Cerebral malaria (coma, seizures)", "Severe anemia", "Kidney failure", "Acute respiratory distress", "Death (especially P. falciparum)"],
        "emergency_signs": ["High fever in a malaria-endemic area", "Confusion or altered consciousness", "Severe anemia (extreme fatigue, pallor)", "Dark/cola-colored urine", "Jaundice", "Difficulty breathing"],
        "when_to_see_doctor": "Immediately if you develop fever after visiting a malaria-endemic area (even months later). Test with blood smear/RDT."
    },
    "tuberculosis": {
        "category": "Infectious/Respiratory",
        "symptoms": ["Persistent cough (>2-3 weeks)", "Coughing up blood or sputum", "Night sweats", "Weight loss", "Loss of appetite", "Low-grade fever", "Fatigue", "Chest pain"],
        "causes": ["Mycobacterium tuberculosis bacterium", "Airborne transmission (droplet nuclei)", "Weakened immune system increases risk", "Close contact with infected person"],
        "treatment": ["Directly Observed Therapy (DOT) — 6 months minimum", "First 2 months: Isoniazid + Rifampicin + Pyrazinamide + Ethambutol", "Remaining 4 months: Isoniazid + Rifampicin", "Complete full course to prevent resistance"],
        "prevention": ["BCG vaccination (childhood)", "Cover mouth when coughing", "Good ventilation", "Latent TB treatment if at risk", "Avoid close contact with active TB patients"],
        "complications": ["Drug-resistant TB (MDR/XDR-TB)", "Spread to brain, kidneys, spine", "Collapsed lung", "Heart complications", "Death if untreated"],
        "emergency_signs": ["Massive hemoptysis (coughing blood)", "Severe chest pain", "Respiratory distress", "Very high fever with altered mental status"],
        "when_to_see_doctor": "If cough lasts more than 2-3 weeks, especially with weight loss, night sweats, or blood in sputum. Early treatment prevents spread."
    },
    "covid-19": {
        "category": "Infectious/Respiratory",
        "symptoms": ["Fever or chills", "Cough", "Shortness of breath", "Fatigue", "Body aches", "Loss of taste or smell", "Sore throat", "Headache", "Nausea or diarrhea", "Congestion"],
        "causes": ["SARS-CoV-2 coronavirus", "Respiratory droplets and aerosols", "Close contact with infected person", "Touching contaminated surfaces"],
        "treatment": ["Rest, hydration, paracetamol for fever", "Antivirals (Paxlovid) if within 5 days and high-risk", "Monoclonal antibodies (selected cases)", "Oxygen therapy if severe", "Hospitalization for critical cases"],
        "prevention": ["Vaccination and boosters", "Masking in crowded/indoor settings", "Hand hygiene", "Ventilation", "Physical distancing during surges"],
        "complications": ["Long COVID (persistent symptoms)", "Pneumonia", "Blood clots", "Heart inflammation (myocarditis)", "Kidney damage", "Neurological effects"],
        "emergency_signs": ["Difficulty breathing", "Persistent chest pain", "Confusion", "Inability to stay awake", "Bluish lips or face", "Oxygen saturation <94%"],
        "when_to_see_doctor": "If you have risk factors (age, comorbidities) and test positive — early antiviral treatment helps. Seek emergency care for breathing difficulty."
    },
    "pneumonia": {
        "category": "Respiratory/Infectious",
        "symptoms": ["Cough with phlegm (yellow/green/bloody)", "Fever with chills", "Shortness of breath", "Chest pain (sharp, worse with breathing)", "Fatigue", "Nausea/vomiting", "Rapid breathing"],
        "causes": ["Bacteria (Streptococcus pneumoniae — most common)", "Viruses (influenza, RSV, COVID-19)", "Fungi (Pneumocystis jirovecii in immunocompromised)", "Aspiration of food/vomit into lungs"],
        "treatment": ["Antibiotics for bacterial pneumonia (Amoxicillin, Azithromycin, Ceftriaxone)", "Antivirals for viral pneumonia", "Antifungals for fungal pneumonia", "Oxygen support if needed", "Hospitalization for severe cases", "Chest physiotherapy"],
        "prevention": ["Pneumococcal vaccine", "Annual flu vaccine", "COVID-19 vaccine", "Hand hygiene", "Avoid smoking", "Good nutrition"],
        "complications": ["Sepsis (blood infection)", "Lung abscess", "Pleural effusion", "Respiratory failure", "Death (especially elderly/immunocompromised)"],
        "emergency_signs": ["Severe difficulty breathing", "Confusion or disorientation", "Very high fever not responding to treatment", "Bluish skin (hypoxia)", "Coughing up blood"],
        "when_to_see_doctor": "Seek immediate care if you have high fever with cough and difficulty breathing. Pneumonia can be life-threatening if untreated."
    },
    "typhoid fever": {
        "category": "Infectious/Gastrointestinal",
        "symptoms": ["Sustained high fever (stepwise pattern)", "Headache", "Abdominal pain", "Constipation or diarrhea", "Rose-colored spots on chest", "Fatigue", "Loss of appetite", "Enlarged liver/spleen"],
        "causes": ["Salmonella typhi bacteria", "Contaminated food or water (fecal-oral route)", "Poor sanitation and hygiene"],
        "treatment": ["Antibiotics: Ciprofloxacin (uncomplicated), Ceftriaxone (severe)", "Azithromycin as alternative", "IV fluids for dehydration", "Soft easily digestible diet", "Monitor for complications"],
        "prevention": ["Safe drinking water (boiled/bottled)", "Proper hand hygiene", "Typhoid vaccine for travelers", "Avoid raw food in endemic areas", "Proper sewage disposal"],
        "complications": ["Intestinal perforation (surgical emergency)", "Bleeding from intestine", "Myocarditis (heart inflammation)", "Meningitis", "Carrier state (chronic)"],
        "emergency_signs": ["Sudden severe abdominal pain", "Signs of intestinal perforation (rigid abdomen)", "Heavy rectal bleeding", "Altered consciousness", "Very high unrelenting fever"],
        "when_to_see_doctor": "If you develop sustained fever after traveling to areas with poor sanitation. Blood culture confirms diagnosis."
    },
    "gout": {
        "category": "Musculoskeletal/Metabolic",
        "symptoms": ["Sudden severe joint pain (often big toe — podagra)", "Swelling and redness", "Warmth over joint", "Extreme tenderness", "Limited range of motion", "Attacks often at night"],
        "causes": ["High uric acid levels (hyperuricemia)", "Diet: red meat, organ meats, shellfish, alcohol (especially beer)", "Dehydration", "Genetics", "Obesity", "Kidney disease", "Certain medications (diuretics)"],
        "treatment": ["Acute: NSAIDs (Naproxen, Indomethacin), Colchicine, Corticosteroids", "Chronic: Allopurinol or Febuxostat (urate-lowering therapy)", "Anti-inflammatory diet", "Weight management", "Stay well-hydrated"],
        "prevention": ["Limit purine-rich foods", "Limit alcohol (especially beer)", "Stay hydrated", "Maintain healthy weight", "Limit sugary drinks", "Regular uric acid monitoring"],
        "complications": ["Tophi (uric acid crystal deposits under skin)", "Kidney stones", "Joint deformity", "Chronic kidney disease", "Cardiovascular disease"],
        "emergency_signs": ["Fever with joint swelling (possible septic arthritis — medical emergency)", "Unable to urinate", "Severe flank pain (kidney stones)"],
        "when_to_see_doctor": "If you experience sudden severe joint pain, especially in the big toe. Repeated attacks warrant long-term uric acid management."
    },
    "bronchitis": {
        "category": "Respiratory",
        "symptoms": ["Persistent cough with mucus", "Chest discomfort", "Fatigue", "Shortness of breath", "Mild fever and chills", "Body aches", "Sore throat"],
        "causes": ["Viral infection (most common — rhinovirus, influenza)", "Bacterial infection (less common)", "Smoking", "Air pollution", "Chemical fumes/dust", "GERD (chronic bronchitis)"],
        "treatment": ["Rest and hydration", "Honey and warm liquids for cough", "Bronchodilators (Salbutamol) if wheezing", "Cough suppressants (nighttime only)", "Antibiotics only if bacterial", "Steam inhalation"],
        "prevention": ["Don't smoke", "Avoid secondhand smoke", "Hand washing", "Flu vaccination", "Avoid air pollution", "Cover mouth when coughing"],
        "complications": ["Pneumonia", "Chronic bronchitis (COPD)", "Asthma exacerbation", "Respiratory failure (rare)"],
        "emergency_signs": ["High fever (>38.5°C) lasting more than 3 days", "Coughing up blood", "Severe difficulty breathing", "Chest pain"],
        "when_to_see_doctor": "If cough lasts more than 3 weeks, or if you cough up blood, or develop high fever with breathing difficulty."
    },
    "sinusitis": {
        "category": "ENT/Respiratory",
        "symptoms": ["Facial pain and pressure (cheeks, forehead)", "Nasal congestion", "Thick yellow/green nasal discharge", "Postnasal drip", "Reduced sense of smell", "Headache (worse when bending forward)", "Cough", "Fatigue"],
        "causes": ["Viral infection (most common — follows cold)", "Bacterial infection (secondary)", "Allergies (allergic sinusitis)", "Nasal polyps", "Deviated nasal septum", "Dental infections"],
        "treatment": ["Saline nasal irrigation (neti pot)", "Nasal decongestant sprays (short-term only — max 3 days)", "Nasal corticosteroid sprays (Fluticasone)", "Steam inhalation", "Antibiotics if bacterial (Amoxicillin-clavulanate)", "Pain relief (Paracetamol, Ibuprofen)"],
        "prevention": ["Treat colds promptly", "Nasal saline rinses during colds", "Avoid known allergens", "Stay hydrated", "Use humidifier"],
        "complications": ["Chronic sinusitis", "Orbital cellulitis (eye infection — dangerous)", "Brain abscess (very rare)", "Meningitis (very rare)"],
        "emergency_signs": ["Swelling around eyes", "Severe headache with high fever", "Vision changes", "Stiff neck", "Confusion"],
        "when_to_see_doctor": "If symptoms last more than 10 days without improvement, or symptoms are severe (high fever, facial swelling)."
    },
    "polycystic ovary syndrome (pcos)": {
        "category": "Endocrine/Reproductive",
        "symptoms": ["Irregular or absent menstrual periods", "Excess hair growth (hirsutism) on face/body", "Acne and oily skin", "Weight gain (especially around waist)", "Difficulty getting pregnant", "Thinning hair on scalp", "Dark patches of skin (acanthosis nigricans)"],
        "causes": ["Exact cause unknown — combination of genetic and environmental factors", "Insulin resistance (key driver)", "Excess androgen production by ovaries", "Low-grade chronic inflammation", "Family history"],
        "treatment": ["Lifestyle: weight loss (even 5-10% helps significantly)", "Metformin for insulin resistance", "Combined oral contraceptive pills (regulate periods, reduce androgens)", "Anti-androgens (Spironolactone) for hair growth/acne", "Fertility treatment (Clomiphene, Letrozole) if trying to conceive", "Inositol supplements (emerging evidence)"],
        "prevention": ["Cannot be prevented but early management reduces complications", "Healthy diet (low glycemic index)", "Regular exercise", "Maintain healthy weight"],
        "complications": ["Type 2 diabetes", "Endometrial cancer (from unopposed estrogen)", "Cardiovascular disease", "Sleep apnea", "Depression and anxiety", "Infertility"],
        "emergency_signs": ["Severe pelvic pain", "Heavy vaginal bleeding", "Symptoms of diabetes (excessive thirst/urination)"],
        "when_to_see_doctor": "If you have irregular periods, excess hair growth, or difficulty conceiving. Early diagnosis and management prevents long-term complications."
    },
    "chickenpox (varicella)": {
        "category": "Infectious",
        "symptoms": ["Itchy blister-like rash (starts on face/trunk, spreads)", "Fever", "Fatigue", "Loss of appetite", "Headache", "Rash progresses: red spots → blisters → scabs"],
        "causes": ["Varicella-zoster virus (VZV)", "Highly contagious — airborne droplets or direct contact with blisters", "Contagious from 1-2 days before rash until all blisters are scabbed"],
        "treatment": ["Acyclovir (if severe or high-risk patients)", "Paracetamol for fever (AVOID aspirin — Reye's syndrome risk)", "Calamine lotion for itch relief", "Antihistamines (Cetirizine) for itching", "Keep nails short to prevent scratching", "Warm oatmeal baths"],
        "prevention": ["Varicella vaccine (2 doses — highly effective)", "Isolation until all blisters scab over", "Avoid contact with susceptible individuals"],
        "complications": ["Secondary bacterial skin infection", "Pneumonia", "Encephalitis (brain inflammation)", "Reye's syndrome (if aspirin used)", "Shingles later in life"],
        "emergency_signs": ["High fever (>39°C) lasting more than 4 days", "Difficulty breathing (possible pneumonia)", "Severe headache with vomiting (possible encephalitis)", "Pus-filled blisters (secondary infection)", "Not eating/drinking"],
        "when_to_see_doctor": "For infants, pregnant women, immunocompromised individuals, or if any emergency signs appear. Adults with chickenpox are at higher risk for complications."
    },
}

# Maps common symptom phrases (lowercase) to candidate diseases above.
SYMPTOM_TO_DISEASE = {
    "frequent urination": ["diabetes", "urinary tract infection"],
    "excessive thirst": ["diabetes"],
    "weight loss": ["diabetes", "depression"],
    "weight gain": ["thyroid disorder (hypothyroidism)"],
    "fatigue": ["diabetes", "anxiety disorder", "depression", "common cold", "fever", "anemia", "thyroid disorder (hypothyroidism)"],
    "blurred vision": ["diabetes"],
    "headache": ["hypertension", "fever", "common cold", "headache", "migraine"],
    "shortness of breath": ["hypertension", "fever", "asthma", "anemia"],
    "high blood pressure": ["hypertension"],
    "fever": ["fever", "common cold", "influenza", "urinary tract infection"],
    "chills": ["fever", "influenza"],
    "runny nose": ["common cold", "allergic rhinitis"],
    "sneezing": ["common cold", "allergic rhinitis"],
    "cough": ["common cold", "influenza", "asthma"],
    "sore throat": ["common cold", "influenza"],
    "nausea": ["fever", "headache", "migraine", "gastroenteritis", "gerd"],
    "vomiting": ["gastroenteritis", "migraine"],
    "diarrhea": ["gastroenteritis"],
    "stress": ["headache", "anxiety disorder", "insomnia"],
    "sleep": ["insomnia"],
    "worry": ["anxiety disorder"],
    "sadness": ["depression"],
    "hopelessness": ["depression"],
    "restlessness": ["anxiety disorder"],
    "panic": ["anxiety disorder"],
    "irritability": ["anxiety disorder", "insomnia", "thyroid disorder (hypothyroidism)"],
    "wheezing": ["asthma"],
    "chest tightness": ["asthma"],
    "heartburn": ["gerd"],
    "burning urination": ["urinary tract infection"],
    "joint pain": ["arthritis"],
    "stiffness": ["arthritis"],
    "pale skin": ["anemia"],
    "cold intolerance": ["thyroid disorder (hypothyroidism)"],
    "hair loss": ["thyroid disorder (hypothyroidism)"],
    "itchy eyes": ["allergic rhinitis"],
    "itchy skin": ["eczema", "urticaria (hives)", "allergic rhinitis"],
    "itching": ["eczema", "urticaria (hives)", "allergic rhinitis", "skin rash"],
    "skin rash": ["eczema", "urticaria (hives)", "skin rash", "allergic rhinitis"],
    "hives": ["urticaria (hives)"],
    "red welts": ["urticaria (hives)"],
    "raised bumps": ["urticaria (hives)", "eczema"],
    "dry skin": ["eczema", "thyroid disorder (hypothyroidism)"],
    "memory loss": ["alzheimer's disease", "depression", "thyroid disorder (hypothyroidism)"],
    "confusion": ["alzheimer's disease", "diabetes", "hypertension", "urinary tract infection"],
    "forgetfulness": ["alzheimer's disease", "depression", "anxiety disorder"],
    "difficulty concentrating": ["depression", "anxiety disorder", "insomnia", "anemia"],
    "mood changes": ["alzheimer's disease", "depression", "anxiety disorder", "thyroid disorder (hypothyroidism)"],
    "personality changes": ["alzheimer's disease", "depression"],
    "muscle pain": ["arthritis", "migraine", "influenza"],
    "body ache": ["influenza", "fever", "common cold"],
    "back pain": ["arthritis", "urinary tract infection"],
    "abdominal pain": ["gastroenteritis", "gerd"],
    "bloating": ["gerd", "gastroenteritis"],
    "constipation": ["thyroid disorder (hypothyroidism)", "depression"],
    "rash": ["eczema", "urticaria (hives)", "skin rash"],
    "dry eyes": ["allergic rhinitis", "thyroid disorder (hypothyroidism)"],
    "nasal congestion": ["common cold", "allergic rhinitis"],
    "postnasal drip": ["allergic rhinitis", "common cold"],
    "sinus pain": ["common cold", "allergic rhinitis"],
    "ear pain": ["common cold", "influenza"],
    "toothache": ["common cold"],
    "eye pain": ["migraine"],
    "sensitivity to light": ["migraine"],
    "throbbing head pain": ["migraine"],
    "swollen glands": ["common cold", "influenza"],
    "night sweats": ["fever", "influenza"],
    "dizziness": ["hypertension", "anemia", "migraine"],
    "loss of appetite": ["depression", "gastroenteritis", "fever"],
    "muscle weakness": ["thyroid disorder (hypothyroidism)", "anemia"],
    "tingling": ["diabetes", "anemia"],
    "numbness": ["diabetes", "hypertension"],
    "cold hands": ["anemia", "thyroid disorder (hypothyroidism)"],
    "brittle nails": ["anemia", "thyroid disorder (hypothyroidism)"],
    "swelling": ["arthritis", "urinary tract infection"],
    "swollen joints": ["arthritis"],
    "knee pain": ["arthritis"],
    "neck pain": ["arthritis", "migraine"],
    "burning sensation": ["urinary tract infection", "diabetes"],
    "frequent headaches": ["hypertension", "migraine"],
    "difficulty breathing": ["asthma", "anemia", "hypertension"],
    "swollen throat": ["allergic rhinitis"],
    "chronic cough": ["asthma", "gerd", "common cold"],
    "acid reflux": ["gerd"],
    "indigestion": ["gerd", "gastroenteritis"],
    "brain fog": ["anxiety disorder", "depression", "insomnia", "thyroid disorder (hypothyroidism)"],
    "tremor": ["anxiety disorder", "thyroid disorder (hypothyroidism)"],
    "palpitations": ["anxiety disorder", "thyroid disorder (hypothyroidism)", "anemia"],
    "loss of interest": ["depression"],
    "social withdrawal": ["depression", "alzheimer's disease"],
    "difficulty finding words": ["alzheimer's disease"],
    "difficulty with familiar tasks": ["alzheimer's disease"],
    "misplacing things": ["alzheimer's disease"],
    "poor judgment": ["alzheimer's disease"],
    "joint swelling": ["gout", "arthritis"],
    "big toe pain": ["gout"],
    "high uric acid": ["gout"],
    "facial pain": ["sinusitis", "migraine"],
    "nasal congestion": ["sinusitis", "common cold", "allergic rhinitis"],
    "facial pressure": ["sinusitis"],
    "green mucus": ["sinusitis", "bronchitis"],
    "chest congestion": ["bronchitis", "pneumonia"],
    "mucus": ["bronchitis", "sinusitis"],
    "blister": ["chickenpox (varicella)"],
    "chickenpox": ["chickenpox (varicella)"],
    "varicella": ["chickenpox (varicella)"],
    "itchy blister": ["chickenpox (varicella)"],
    "irregular period": ["polycystic ovary syndrome (pcos)"],
    "pcos": ["polycystic ovary syndrome (pcos)"],
    "hirsutism": ["polycystic ovary syndrome (pcos)"],
    "excess hair": ["polycystic ovary syndrome (pcos)"],
    "mosquito bite": ["dengue fever", "malaria"],
    "joint pain fever": ["dengue fever", "chikungunya", "malaria"],
    "breakbone": ["dengue fever"],
    "chills sweating": ["malaria", "dengue fever"],
    "night sweat": ["tuberculosis", "malaria", "influenza"],
    "persistent cough": ["tuberculosis", "bronchitis", "asthma", "pneumonia"],
    "cough blood": ["tuberculosis", "pneumonia"],
    "coughing blood": ["tuberculosis", "pneumonia"],
    "night sweat weight loss": ["tuberculosis"],
    "covid": ["covid-19"],
    "coronavirus": ["covid-19"],
    "loss taste": ["covid-19"],
    "loss smell": ["covid-19", "common cold"],
    "shortness": ["pneumonia", "asthma", "bronchitis", "heart failure"],
    "phlegm": ["bronchitis", "pneumonia", "tuberculosis"],
    "sustained fever": ["typhoid fever", "malaria", "tuberculosis"],
    "rose spots": ["typhoid fever"],
    "typhoid": ["typhoid fever"],
    "abdominal pain fever": ["typhoid fever", "malaria"],
}

# Curated offline medicines — used as instant fallback if openFDA is
# unreachable, and to guarantee good answers for the most common drugs.
LOCAL_MEDICINES = [
    {
        "id": "paracetamol", "name": "Paracetamol", "brand": "Crocin, Calpol, Dolo, Tylenol, Panadol, Febrectol",
        "category": "Analgesic, Antipyretic",
        "uses": ["Fever", "Headache", "Mild to moderate pain", "Body ache", "Toothache", "Menstrual pain"],
        "symptoms_treated": ["Fever", "Headache", "Body ache", "Toothache", "Menstrual cramps"],
        "side_effects": {"common": ["Nausea", "Stomach upset"], "serious": ["Liver damage (overdose)", "Allergic reactions"]},
        "dosage": {"adult": "500-1000mg every 6-8 hours. Max 4g/day", "child": "15mg/kg every 6-8 hours", "elderly": "Same as adult, monitor liver function"},
        "how_to_use": "Take with or after food. Do not exceed recommended dose.",
        "precautions": ["Avoid if you have liver disease", "Do not drink alcohol", "Do not take with other paracetamol-containing products"],
        "interactions": ["Blood thinners (warfarin) - increased bleeding risk", "Alcohol - increased liver damage risk"],
        "pregnancy": "Generally considered safe when used as directed. Consult doctor.",
        "breastfeeding": "Safe in normal doses, consult doctor.", "source": "Curated reference"
    },
    {
        "id": "amoxicillin", "name": "Amoxicillin", "brand": "Amoxil, Mox, Novamox, Trimox, Amox",
        "category": "Antibiotic, Penicillin-class",
        "uses": ["Bacterial infections", "Throat infection", "Sinusitis", "Urinary tract infection", "Ear infection"],
        "symptoms_treated": ["Sore throat", "Fever with infection", "Ear pain", "Sinus pain"],
        "side_effects": {"common": ["Diarrhea", "Nausea", "Vomiting", "Skin rash"], "serious": ["Severe allergic reactions", "C. difficile infection"]},
        "dosage": {"adult": "250-500mg every 8 hours", "child": "20-45mg/kg/day in divided doses", "elderly": "Dose adjustment for kidney problems"},
        "how_to_use": "Complete full course even if symptoms improve. Take with food.",
        "precautions": ["Inform doctor if allergic to penicillin", "Inform doctor if you have kidney disease"],
        "interactions": ["Oral contraceptives - may reduce effectiveness", "Allopurinol - increased rash risk"],
        "pregnancy": "Generally considered safe during pregnancy. Consult doctor.",
        "breastfeeding": "Safe during breastfeeding.", "source": "Curated reference"
    },
    {
        "id": "ibuprofen", "name": "Ibuprofen", "brand": "Brufen, Advil, Motrin, Combiflam, Ibugesic",
        "category": "NSAID, Anti-inflammatory",
        "uses": ["Pain", "Inflammation", "Fever", "Arthritis", "Menstrual cramps", "Muscle pain"],
        "symptoms_treated": ["Joint pain", "Muscle pain", "Menstrual cramps", "Fever", "Inflammation"],
        "side_effects": {"common": ["Stomach upset", "Heartburn", "Nausea", "Dizziness"], "serious": ["Stomach ulcer/bleeding", "Kidney problems"]},
        "dosage": {"adult": "200-400mg every 6-8 hours. Max 1.2g/day OTC", "child": "5-10mg/kg every 6-8 hours", "elderly": "Use lowest effective dose"},
        "how_to_use": "Always take after meals. Use lowest effective dose for shortest duration.",
        "precautions": ["Avoid in stomach ulcers", "Avoid in kidney disease", "Avoid in heart problems", "Avoid in late pregnancy"],
        "interactions": ["Blood thinners - increased bleeding risk", "Aspirin - reduced cardioprotective effect"],
        "pregnancy": "Avoid in third trimester; use with caution earlier.",
        "breastfeeding": "Generally compatible in low doses, consult doctor.", "source": "Curated reference"
    },
    {
        "id": "cetirizine", "name": "Cetirizine", "brand": "Zyrtec, Cetrine, Alerid, CTZ",
        "category": "Antihistamine",
        "uses": ["Allergies", "Hay fever", "Allergic rhinitis", "Urticaria (hives)", "Itching", "Skin rash", "Eczema"],
        "symptoms_treated": ["Sneezing", "Runny nose", "Itchy eyes", "Itchy skin", "Skin rash", "Hives", "Itching"],
        "side_effects": {"common": ["Drowsiness", "Dry mouth", "Fatigue"], "serious": ["Severe allergic reactions (rare)"]},
        "dosage": {"adult": "10mg once daily", "child": "2.5-5mg once daily (6-12 years)", "elderly": "Start with 5mg once daily"},
        "how_to_use": "Can be taken with or without food. Take at the same time each day.",
        "precautions": ["Avoid driving if drowsy", "Inform doctor if you have kidney disease", "Avoid alcohol"],
        "interactions": ["Alcohol - increased drowsiness", "Sedatives - increased drowsiness"],
        "pregnancy": "Use only if clearly needed, consult doctor.",
        "breastfeeding": "Small amounts pass into breast milk, use with caution.", "source": "Curated reference"
    },
    {
        "id": "pheniramine", "name": "Pheniramine", "brand": "Avil, Aller-AF, Demazin, Phenadoz",
        "category": "Antihistamine",
        "uses": ["Allergies", "Hay fever", "Urticaria (hives)", "Itching", "Skin rash", "Common cold symptoms", "Motion sickness"],
        "symptoms_treated": ["Sneezing", "Runny nose", "Itchy eyes", "Itchy skin", "Skin rash", "Hives", "Itching", "Nasal congestion"],
        "side_effects": {"common": ["Drowsiness", "Dry mouth", "Dizziness", "Blurred vision"], "serious": ["Severe allergic reactions (rare)", "Urinary retention (rare)"]},
        "dosage": {"adult": "25mg every 6-8 hours (max 150mg/day)", "child": "12.5mg every 6-8 hours (6-12 years)", "elderly": "Start with lower dose, 12.5-25mg"},
        "how_to_use": "Take with food to reduce stomach upset. Avoid driving or operating machinery.",
        "precautions": ["Avoid driving if drowsy", "Avoid alcohol", "Caution in glaucoma, prostate enlargement", "Not recommended for elderly at high doses"],
        "interactions": ["Alcohol - increased drowsiness", "MAO inhibitors - avoid combination", "Sedatives - increased drowsiness"],
        "pregnancy": "Use only if clearly needed. Consult doctor.",
        "breastfeeding": "Small amounts pass into breast milk. Use with caution.", "source": "Curated reference"
    },
    {
        "id": "loratadine", "name": "Loratadine", "brand": "Claritin, Allegra-L, Lorid",
        "category": "Antihistamine (Non-drowsy)",
        "uses": ["Allergies", "Hay fever", "Urticaria (hives)", "Itching", "Skin rash", "Runny nose"],
        "symptoms_treated": ["Sneezing", "Runny nose", "Itchy eyes", "Itchy skin", "Hives", "Itching"],
        "side_effects": {"common": ["Headache", "Drowsiness (rare)", "Dry mouth"], "serious": ["Severe allergic reactions (very rare)"]},
        "dosage": {"adult": "10mg once daily", "child": "5mg once daily (2-12 years)", "elderly": "10mg once daily (no adjustment needed)"},
        "how_to_use": "Can be taken with or without food. Does not typically cause drowsiness.",
        "precautions": ["Generally well-tolerated", "Adjust dose for severe liver disease"],
        "interactions": ["Erythromycin - slight increase in levels", "Cimetidine - slight increase in levels"],
        "pregnancy": "Considered safe in pregnancy. Consult doctor.",
        "breastfeeding": "Secreted in breast milk; use with caution.", "source": "Curated reference"
    },
    {
        "id": "metformin", "name": "Metformin", "brand": "Glycomet, Glucophage, Metmin",
        "category": "Antidiabetic (Biguanide)",
        "uses": ["Type 2 diabetes", "Polycystic ovary syndrome", "Prediabetes"],
        "symptoms_treated": ["High blood sugar", "Excessive thirst", "Frequent urination", "Fatigue"],
        "side_effects": {"common": ["Nausea", "Diarrhea", "Stomach upset"], "serious": ["Lactic acidosis (rare)", "Vitamin B12 deficiency (long-term)"]},
        "dosage": {"adult": "500mg twice daily, titrated up; or 850mg once daily", "child": "Children 10-16: 500-1000mg twice daily", "elderly": "Start with lower dose"},
        "how_to_use": "Take with meals to reduce stomach side effects.",
        "precautions": ["Inform doctor if you have kidney disease", "Inform doctor if you have liver disease", "Stop before contrast imaging procedures"],
        "interactions": ["Alcohol - increased lactic acidosis risk", "Contrast media - increased lactic acidosis risk"],
        "pregnancy": "Sometimes used under medical supervision; consult doctor.",
        "breastfeeding": "Generally considered compatible with breastfeeding.", "source": "Curated reference"
    },
    {
        "id": "omeprazole", "name": "Omeprazole", "brand": "Prilosec, Omez, Ocid",
        "category": "Proton Pump Inhibitor (PPI)",
        "uses": ["GERD", "Acid reflux", "Stomach ulcers", "H. pylori treatment (combo therapy)"],
        "symptoms_treated": ["Heartburn", "Acid regurgitation", "Stomach pain"],
        "side_effects": {"common": ["Headache", "Nausea", "Abdominal pain", "Diarrhea"], "serious": ["Increased fracture risk (long-term)", "Low magnesium (long-term)"]},
        "dosage": {"adult": "20-40mg once daily before breakfast", "child": "Weight-based, consult pediatrician", "elderly": "Same as adult, monitor long-term use"},
        "how_to_use": "Take 30-60 minutes before a meal, preferably breakfast. Swallow whole, don't crush.",
        "precautions": ["Long-term use needs medical supervision", "May mask symptoms of stomach cancer"],
        "interactions": ["Clopidogrel - reduced effectiveness", "Certain antifungals - altered absorption"],
        "pregnancy": "Generally considered safe, consult doctor.",
        "breastfeeding": "Limited data; consult doctor.", "source": "Curated reference"
    },
    {
        "id": "salbutamol", "name": "Salbutamol", "brand": "Ventolin, Asthalin, ProAir",
        "category": "Bronchodilator (SABA)",
        "uses": ["Asthma", "COPD", "Exercise-induced bronchospasm"],
        "symptoms_treated": ["Wheezing", "Shortness of breath", "Chest tightness"],
        "side_effects": {"common": ["Tremor", "Rapid heartbeat", "Headache", "Nervousness"], "serious": ["Severe allergic reaction (rare)", "Paradoxical bronchospasm (rare)"]},
        "dosage": {"adult": "1-2 puffs (100-200mcg) as needed, max 8 puffs/day", "child": "1-2 puffs as needed under guidance", "elderly": "Same as adult"},
        "how_to_use": "Use inhaler as directed; shake well before use; rinse mouth after use.",
        "precautions": ["Overuse may indicate poor asthma control — see a doctor", "Caution with heart conditions"],
        "interactions": ["Beta-blockers - reduced effectiveness", "Diuretics - low potassium risk"],
        "pregnancy": "Generally considered safe when needed, consult doctor.",
        "breastfeeding": "Generally considered compatible.", "source": "Curated reference"
    },
    {
        "id": "levothyroxine", "name": "Levothyroxine", "brand": "Synthroid, Eltroxin, Thyronorm",
        "category": "Thyroid Hormone Replacement",
        "uses": ["Hypothyroidism", "Goiter (some cases)", "Thyroid cancer (post-surgery)"],
        "symptoms_treated": ["Fatigue", "Weight gain", "Cold intolerance", "Hair loss"],
        "side_effects": {"common": ["Headache (overdose)", "Insomnia (overdose)"], "serious": ["Heart palpitations (overdose)", "Bone density loss (long-term overdose)"]},
        "dosage": {"adult": "Typically 25-200mcg once daily, individualized via blood tests", "child": "Weight-based, pediatric endocrinologist guidance", "elderly": "Start low, go slow"},
        "how_to_use": "Take on empty stomach, 30-60 minutes before breakfast, with water only.",
        "precautions": ["Avoid taking with calcium/iron supplements (separate by 4 hours)", "Regular thyroid function monitoring required"],
        "interactions": ["Calcium/iron supplements - reduced absorption", "Warfarin - altered effect"],
        "pregnancy": "Often dose-adjusted during pregnancy under medical care.",
        "breastfeeding": "Generally considered safe and necessary if needed.", "source": "Curated reference"
    },
    {
        "id": "diclofenac", "name": "Diclofenac", "brand": "Volini, Voveran, Dicloran, Cataflam",
        "category": "NSAID, Anti-inflammatory",
        "uses": ["Pain", "Inflammation", "Arthritis", "Muscle pain", "Sprains", "Dental pain", "Migraine"],
        "symptoms_treated": ["Joint pain", "Muscle pain", "Back pain", "Swelling", "Inflammation"],
        "side_effects": {"common": ["Stomach upset", "Nausea", "Dizziness", "Skin rash at application site"], "serious": ["Stomach ulcer/bleeding", "Kidney problems", "Cardiovascular events (long-term oral use)"]},
        "dosage": {"adult": "25-50mg 2-3 times daily (oral); gel applied 3-4 times daily", "child": "0.5-2mg/kg/day in divided doses", "elderly": "Use lowest effective dose for shortest duration"},
        "how_to_use": "Take with food if oral. Apply gel thinly to affected area. Do not use on broken skin.",
        "precautions": ["Avoid in stomach ulcers", "Avoid in kidney disease", "Avoid in heart problems", "Avoid in late pregnancy", "Do not combine with other NSAIDs"],
        "interactions": ["Blood thinners - increased bleeding risk", "Lithium - increased levels", "Methotrexate - increased toxicity"],
        "pregnancy": "Avoid especially in third trimester. Consult doctor.",
        "breastfeeding": "Avoid topical use near breasts; oral use not recommended.", "source": "Curated reference"
    },
    {
        "id": "pantoprazole", "name": "Pantoprazole", "brand": "Pantop, Pan, Pantodac, Razo, PPI-40",
        "category": "Proton Pump Inhibitor (PPI)",
        "uses": ["GERD", "Acid reflux", "Zollinger-Ellison syndrome", "Stress ulcer prevention", "H. pylori eradication (combo)"],
        "symptoms_treated": ["Heartburn", "Acid regurgitation", "Stomach pain", "Bloating"],
        "side_effects": {"common": ["Headache", "Nausea", "Abdominal pain", "Diarrhea", "Flatulence"], "serious": ["Bone fractures (long-term)", "Vitamin B12 deficiency (long-term)", "Low magnesium (long-term)"]},
        "dosage": {"adult": "40mg once daily before breakfast (can increase to 80mg)", "child": "Weight-based, consult pediatrician", "elderly": "20-40mg once daily"},
        "how_to_use": "Take 30-60 minutes before a meal. Swallow whole, do not crush or chew.",
        "precautions": ["Long-term use needs medical supervision", "May mask gastric cancer symptoms", "Not for immediate heartburn relief"],
        "interactions": ["Methotrexate - increased levels", "Clopidogrel - reduced effectiveness", "Atazanavir - avoid combination"],
        "pregnancy": "Use only if clearly needed. Consult doctor.",
        "breastfeeding": "Limited data; consult doctor.", "source": "Curated reference"
    },
    {
        "id": "azithromycin", "name": "Azithromycin", "brand": "Azee, Azithral, Zithromax, Zmax",
        "category": "Antibiotic, Macrolide",
        "uses": ["Bacterial infections", "Throat infection", "Respiratory infections", "Skin infections", "Ear infections", "Sexually transmitted infections"],
        "symptoms_treated": ["Sore throat", "Fever with infection", "Cough with infection", "Ear pain", "Skin infection"],
        "side_effects": {"common": ["Diarrhea", "Nausea", "Stomach pain", "Headache"], "serious": ["Severe allergic reactions", "Heart rhythm problems (rare)", "Liver problems (rare)"]},
        "dosage": {"adult": "500mg day 1, then 250mg daily for 4 days (Z-pack); or 500mg once weekly for 3 weeks", "child": "10mg/kg day 1, then 5mg/kg daily for 4 days", "elderly": "Same as adult, monitor heart rhythm"},
        "how_to_use": "Can be taken with or without food. Complete the full course as prescribed.",
        "precautions": ["Inform doctor if you have liver or heart disease", "Avoid in severe kidney disease", "Report irregular heartbeat"],
        "interactions": ["Antacids - reduce absorption", "Blood thinners (warfarin) - may increase effect", "Digoxin - increased levels"],
        "pregnancy": "Generally considered safe. Consult doctor.",
        "breastfeeding": "Small amounts in breast milk; use with caution.", "source": "Curated reference"
    },
    {
        "id": "nimesulide", "name": "Nimesulide", "brand": "Nise, Nisolide, Nicide, Nimulid",
        "category": "NSAID, Anti-inflammatory",
        "uses": ["Pain", "Inflammation", "Fever", "Dental pain", "Musculoskeletal pain", "Osteoarthritis"],
        "symptoms_treated": ["Joint pain", "Muscle pain", "Back pain", "Toothache", "Fever", "Inflammation"],
        "side_effects": {"common": ["Nausea", "Stomach upset", "Diarrhea", "Dizziness"], "serious": ["Liver damage (rare)", "Stomach ulcer/bleeding", "Kidney problems"]},
        "dosage": {"adult": "100mg twice daily after meals (max 200mg/day)", "child": "5mg/kg twice daily (not recommended under 12 years in some countries)", "elderly": "Use lowest effective dose"},
        "how_to_use": "Take after food. Use for shortest duration necessary. Max 15 days without medical advice.",
        "precautions": ["Avoid in liver disease", "Avoid in kidney disease", "Avoid in heart problems", "Not recommended in children under 12 in many countries", "Short-term use only"],
        "interactions": ["Blood thinners - increased bleeding risk", "Lithium - increased levels", "Diuretics - reduced effect"],
        "pregnancy": "Contraindicated in third trimester. Consult doctor.",
        "breastfeeding": "Not recommended during breastfeeding.", "source": "Curated reference"
    },
    {
        "id": "metronidazole", "name": "Metronidazole", "brand": "Flagyl, Metrogyl, Nidazol, Metrozole",
        "category": "Antibiotic, Antiprotozoal",
        "uses": ["Bacterial infections", "Amoebiasis", "Giardiasis", "H. pylori infection", "Dental infections", "Pelvic inflammatory disease", "Trichomoniasis"],
        "symptoms_treated": ["Diarrhea", "Abdominal pain", "Nausea", "Vomiting", "Fever with infection"],
        "side_effects": {"common": ["Nausea", "Metallic taste", "Loss of appetite", "Diarrhea"], "serious": ["Seizures (high doses)", "Peripheral neuropathy (prolonged use)", "Severe allergic reactions"]},
        "dosage": {"adult": "400-800mg 2-3 times daily (depending on infection)", "child": "7.5mg/kg every 8 hours", "elderly": "Adjust for severe liver disease"},
        "how_to_use": "Take with food. Do not drink alcohol during and for 48 hours after treatment.",
        "precautions": ["Do not consume alcohol (severe reaction: nausea, vomiting, flushing)", "Avoid prolonged use", "Report numbness or tingling"],
        "interactions": ["Alcohol - disulfiram-like reaction (severe)", "Warfarin - increased effect", "Lithium - increased levels"],
        "pregnancy": "Use only if clearly needed, especially in first trimester. Consult doctor.",
        "breastfeeding": "Small amounts in breast milk; consult doctor.", "source": "Curated reference"
    },
    {
        "id": "ciprofloxacin", "name": "Ciprofloxacin", "brand": "Ciproxin, Ciplox, Cipro",
        "category": "Antibiotic, Fluoroquinolone",
        "uses": ["Urinary tract infection", "Respiratory infections", "Skin infections", "Bone/joint infections", "Typhoid fever", "Gastrointestinal infections"],
        "symptoms_treated": ["Burning urination", "Frequent urination", "Fever with infection", "Cough with infection", "Skin infection"],
        "side_effects": {"common": ["Nausea", "Diarrhea", "Headache", "Dizziness"], "serious": ["Tendon rupture (rare)", "Heart rhythm problems", "Seizures (rare)"]},
        "dosage": {"adult": "250-750mg every 12 hours for 7-14 days", "child": "10-20mg/kg every 12 hours (not for children under 12 normally)", "elderly": "Use lowest effective dose; adjust for kidney function"},
        "how_to_use": "Take with or without food. Drink plenty of fluids. Avoid dairy/antacids within 2 hours.",
        "precautions": ["Avoid in tendon disorders", "Avoid in seizure disorders", "Avoid in kidney disease without dose adjustment", "Photosensitivity — use sunscreen"],
        "interactions": ["Antacids/calcium/iron — reduced absorption", "Theophylline — increased levels", "Blood thinners — increased effect"],
        "pregnancy": "Generally avoided unless benefits outweigh risks. Consult doctor.",
        "breastfeeding": "Not recommended; small amounts pass into breast milk.", "source": "Curated reference"
    },
    {
        "id": "amlodipine", "name": "Amlodipine", "brand": "Norvasc, Amlodac, Amlokind, Stamlo",
        "category": "Calcium Channel Blocker",
        "uses": ["High blood pressure", "Angina (chest pain)", "Coronary artery disease"],
        "symptoms_treated": ["High blood pressure", "Chest pain", "Shortness of breath on exertion"],
        "side_effects": {"common": ["Ankle swelling", "Dizziness", "Flushing", "Headache", "Fatigue"], "serious": ["Severe hypotension (rare)", "Heart failure worsening (rare)"]},
        "dosage": {"adult": "5-10mg once daily", "child": "6-17 years: 2.5-5mg once daily", "elderly": "Start with 2.5mg once daily"},
        "how_to_use": "Take at the same time each day, with or without food. Do not stop abruptly.",
        "precautions": ["Avoid stopping suddenly — taper under medical guidance", "Caution in severe heart failure", "Caution with liver disease"],
        "interactions": ["Simvastatin — increased statin levels", "Cyclosporine — increased levels", "Other blood pressure drugs — additive effect"],
        "pregnancy": "Use only if clearly needed. Consult doctor.",
        "breastfeeding": "Small amounts in breast milk; use with caution.", "source": "Curated reference"
    },
    {
        "id": "atorvastatin", "name": "Atorvastatin", "brand": "Lipitor, Atorva, Stator, Atorvast",
        "category": "Statin (HMG-CoA Reductase Inhibitor)",
        "uses": ["High cholesterol", "Cardiovascular disease prevention", "Hyperlipidemia"],
        "symptoms_treated": ["High LDL cholesterol", "High triglycerides", "Cardiovascular risk reduction"],
        "side_effects": {"common": ["Muscle pain", "Headache", "Nausea", "Diarrhea"], "serious": ["Rhabdomyolysis (severe muscle breakdown — rare)", "Liver damage (rare)", "Memory problems (rare)"]},
        "dosage": {"adult": "10-80mg once daily (usually at bedtime)", "child": "10-17 years: 10mg once daily", "elderly": "Start with 10mg, adjust based on cholesterol levels"},
        "how_to_use": "Take at any time of day, consistently. Avoid grapefruit juice in large amounts.",
        "precautions": ["Report unexplained muscle pain/weakness immediately", "Regular liver function tests", "Avoid in pregnancy", "Limit alcohol"],
        "interactions": ["Grapefruit juice — increased levels", "Certain antibiotics — increased risk of muscle damage", "Fibrates — increased risk of muscle damage"],
        "pregnancy": "Contraindicated in pregnancy.",
        "breastfeeding": "Not recommended during breastfeeding.", "source": "Curated reference"
    },
    {
        "id": "losartan", "name": "Losartan", "brand": "Cozaar, Losar, Lozak, Losartan-H",
        "category": "Angiotensin II Receptor Blocker (ARB)",
        "uses": ["High blood pressure", "Diabetic nephropathy", "Heart failure", "Stroke prevention"],
        "symptoms_treated": ["High blood pressure", "Kidney protection in diabetes"],
        "side_effects": {"common": ["Dizziness", "Upper respiratory infection", "Back pain"], "serious": ["Hyperkalemia (high potassium)", "Kidney function changes", "Angioedema (rare)"]},
        "dosage": {"adult": "25-100mg once or twice daily", "child": "6-17 years: 0.7mg/kg once daily (max 50mg)", "elderly": "Start with 25mg once daily"},
        "how_to_use": "Take with or without food. Monitor potassium levels. Avoid potassium supplements without doctor advice.",
        "precautions": ["Do not use in pregnancy — cause fetal harm", "Monitor kidney function and potassium", "Avoid in bilateral renal artery stenosis"],
        "interactions": ["Potassium supplements — hyperkalemia risk", "NSAIDs — reduced effectiveness and kidney risk", "Lithium — increased levels"],
        "pregnancy": "CONTRAINDICATED — causes fetal injury/death.",
        "breastfeeding": "Not recommended; limited data.", "source": "Curated reference"
    },
    {
        "id": "montelukast", "name": "Montelukast", "brand": "Singulair, Montair, Montek, Kast",
        "category": "Leukotriene Receptor Antagonist",
        "uses": ["Asthma prevention", "Exercise-induced bronchospasm", "Allergic rhinitis"],
        "symptoms_treated": ["Wheezing", "Shortness of breath", "Chest tightness", "Nasal congestion", "Sneezing"],
        "side_effects": {"common": ["Headache", "Upper respiratory infection", "Cough", "Abdominal pain"], "serious": ["Mood changes, depression, suicidal thoughts (rare — FDA boxed warning)", "Severe allergic reactions (rare)"]},
        "dosage": {"adult": "10mg once daily (evening)", "child": "6-14 years: 5mg chewable tablet; 2-5 years: 4mg granules", "elderly": "10mg once daily"},
        "how_to_use": "Take in the evening. Not for acute asthma attacks — use rescue inhaler. Chewable tablet for children.",
        "precautions": ["Report any mood changes or behavioral effects immediately", "Not a substitute for inhaled corticosteroids in moderate-severe asthma", "Use with caution if history of depression"],
        "interactions": ["Phenobarbital — reduced levels", "Gemfibrozil — increased levels", "CYP3A4 inducers — reduced effectiveness"],
        "pregnancy": "Use only if clearly needed. Consult doctor.",
        "breastfeeding": "Small amounts in breast milk; use with caution.", "source": "Curated reference"
    },
    {
        "id": "sertraline", "name": "Sertraline", "brand": "Zoloft, Serta, Deprax, Lustral",
        "category": "SSRI Antidepressant",
        "uses": ["Major depressive disorder", "Anxiety disorder", "OCD", "PTSD", "Panic disorder", "Social anxiety disorder", "PMDD"],
        "symptoms_treated": ["Persistent sadness", "Excessive worry", "Panic attacks", "Obsessive thoughts", "Social anxiety", "Irritability"],
        "side_effects": {"common": ["Nausea", "Diarrhea", "Dizziness", "Insomnia", "Dry mouth", "Sexual dysfunction", "Drowsiness"], "serious": ["Suicidal thoughts (especially in young adults — FDA boxed warning)", "Serotonin syndrome (rare)", "Abnormal bleeding"]},
        "dosage": {"adult": "Start 50mg once daily; increase by 25-50mg every 1-2 weeks; max 200mg/day", "child": "OCD: 25mg once daily (6-12 years)", "elderly": "Start with 25mg once daily"},
        "how_to_use": "Take with or without food, preferably in the morning. Do not stop abruptly — taper over 1-2 weeks.",
        "precautions": ["Do not stop suddenly — taper slowly under supervision", "Monitor for worsening depression/suicidal thoughts (especially first 4 weeks)", "Avoid alcohol", "Report any unusual bleeding or bruising"],
        "interactions": ["MAO inhibitors — SEROTONIN SYNDROME (NEVER combine)", "NSAIDs/blood thinners — increased bleeding risk", "Tramadol — seizure risk", "Triptans — serotonin syndrome risk"],
        "pregnancy": "Use only if benefits outweigh risks. Third trimester use may cause neonatal complications.",
        "breastfeeding": "Small amounts in breast milk; generally considered compatible.", "source": "Curated reference"
    },
    {
        "id": "escitalopram", "name": "Escitalopram", "brand": "Lexapro, Cipralex, Esita, Eslice",
        "category": "SSRI Antidepressant",
        "uses": ["Major depressive disorder", "Generalized anxiety disorder", "Social anxiety disorder", "Panic disorder", "OCD"],
        "symptoms_treated": ["Persistent sadness", "Excessive worry", "Panic attacks", "Social anxiety", "Loss of interest"],
        "side_effects": {"common": ["Nausea", "Headache", "Drowsiness", "Insomnia", "Sexual dysfunction", "Dry mouth"], "serious": ["Suicidal thoughts (FDA boxed warning)", "Serotonin syndrome (rare)", "QT prolongation (high doses)"]},
        "dosage": {"adult": "Start 10mg once daily; max 20mg/day", "child": "12-17 years: 10mg once daily", "elderly": "Start with 5mg once daily; max 10mg"},
        "how_to_use": "Take at any time, with or without food. Do not stop abruptly — taper over 1-2 weeks.",
        "precautions": ["Do not stop suddenly — taper slowly", "Monitor for suicidal thoughts (first 4 weeks)", "Avoid alcohol", "Caution in heart disease (QT prolongation at high doses)"],
        "interactions": ["MAO inhibitors — SEROTONIN SYNDROME (NEVER combine)", "NSAIDs/blood thinners — increased bleeding risk", "Pimozide — avoid combination"],
        "pregnancy": "Use only if benefits outweigh risks. Consult doctor.",
        "breastfeeding": "Small amounts in breast milk; use with caution.", "source": "Curated reference"
    },
    {
        "id": "metoprolol", "name": "Metoprolol", "brand": "Lopressor, Toprol-XL, Betaloc, Metolar",
        "category": "Beta-Blocker",
        "uses": ["High blood pressure", "Angina", "Heart failure", "Heart attack prevention", "Irregular heartbeat (arrhythmia)", "Migraine prevention"],
        "symptoms_treated": ["High blood pressure", "Chest pain", "Rapid heartbeat", "Palpitations", "Migraine prevention"],
        "side_effects": {"common": ["Fatigue", "Dizziness", "Cold hands/feet", "Slow heartbeat", "Depression"], "serious": ["Heart failure worsening", "Severe bradycardia", "Bronchospasm"]},
        "dosage": {"adult": "Hypertension: 25-100mg twice daily or 50-200mg extended release once daily", "child": "1-6mg/kg/day in divided doses", "elderly": "Start with 25mg twice daily"},
        "how_to_use": "Take with food. Extended release tablets can be split but not crushed. Do not stop abruptly.",
        "precautions": ["Do not stop suddenly — can cause rebound hypertension and heart attack", "Avoid in severe asthma", "Mask hypoglycemia symptoms in diabetics", "Monitor heart rate"],
        "interactions": ["Calcium channel blockers (verapamil, diltiazem) — dangerous heart block", "Digoxin — increased bradycardia risk", "Clonidine — rebound hypertension if stopped"],
        "pregnancy": "Use only if clearly needed. Consult doctor.",
        "breastfeeding": "Small amounts in breast milk; generally compatible.", "source": "Curated reference"
    },
    {
        "id": "naproxen", "name": "Naproxen", "brand": "Naprosyn, Aleve, Naprelan, Synflex",
        "category": "NSAID, Anti-inflammatory",
        "uses": ["Pain", "Inflammation", "Fever", "Arthritis (osteo and rheumatoid)", "Menstrual cramps", "Gout", "Headache", "Tendonitis"],
        "symptoms_treated": ["Joint pain", "Muscle pain", "Back pain", "Menstrual cramps", "Fever", "Swelling", "Inflammation"],
        "side_effects": {"common": ["Stomach upset", "Heartburn", "Nausea", "Dizziness", "Headache"], "serious": ["Stomach ulcer/bleeding", "Kidney problems", "Cardiovascular events (long-term use)", "Liver damage (rare)"]},
        "dosage": {"adult": "220-440mg every 8-12 hours; max 660mg/day OTC, 1000mg/day prescription", "child": "5-7mg/kg every 8-12 hours (max 20mg/kg/day)", "elderly": "Use lowest effective dose for shortest duration"},
        "how_to_use": "Take with food and a full glass of water. Longer-acting than ibuprofen — dosing every 12 hours possible.",
        "precautions": ["Avoid in stomach ulcers", "Avoid in kidney disease", "Avoid in heart failure", "Avoid in late pregnancy", "Do not combine with other NSAIDs or aspirin"],
        "interactions": ["Blood thinners — increased bleeding risk", "Aspirin — reduced cardioprotective effect", "Lithium — increased levels", "Methotrexate — increased toxicity"],
        "pregnancy": "Avoid in third trimester; use with caution earlier.",
        "breastfeeding": "Generally compatible in low doses; consult doctor.", "source": "Curated reference"
    },
    {
        "id": "ranitidine", "name": "Ranitidine", "brand": "Zantac, Ranitin, Gasrid, Rantac",
        "category": "H2 Receptor Antagonist",
        "uses": ["GERD", "Stomach ulcers", "Heartburn", "Acid indigestion", "H. pylori eradication (combo)", "Zollinger-Ellison syndrome"],
        "symptoms_treated": ["Heartburn", "Acid regurgitation", "Stomach pain", "Indigestion"],
        "side_effects": {"common": ["Headache", "Dizziness", "Constipation", "Diarrhea"], "serious": ["NDMA impurity concerns (recall in some countries)", "Confusion (elderly)", "Liver problems (rare)"]},
        "dosage": {"adult": "75-150mg twice daily or 300mg at bedtime", "child": "2-4mg/kg twice daily (max 300mg/day)", "elderly": "150mg at bedtime or twice daily"},
        "how_to_use": "Take with or without food. For bedtime dosing, take at least 30 minutes before lying down.",
        "precautions": ["Check local availability (NDMA recall in some regions)", "Adjust dose for kidney disease", "May mask symptoms of stomach cancer"],
        "interactions": ["Ketoconazole — reduced absorption", "Antacids — take separately", "Some drugs requiring acidic stomach — reduced absorption"],
        "pregnancy": "Generally considered safe. Consult doctor.",
        "breastfeeding": "Small amounts in breast milk; generally compatible.", "source": "Curated reference"
    },
]

EMERGENCY_CONTACTS = [
    {"country": "India", "ambulance": "102", "police": "100", "fire": "101", "emergency_medical": "108", "mental_health_helpline": "9152987821 (AASRA)", "poison_control": "1066"},
    {"country": "USA", "ambulance": "911", "police": "911", "fire": "911", "emergency_medical": "911", "mental_health_helpline": "988 (Suicide & Crisis Lifeline)", "poison_control": "1-800-222-1222"},
    {"country": "UK", "ambulance": "999", "police": "999", "fire": "999", "emergency_medical": "999", "mental_health_helpline": "116123 (Samaritans)", "poison_control": "111 (NHS)"},
    {"country": "Canada", "ambulance": "911", "police": "911", "fire": "911", "emergency_medical": "911", "mental_health_helpline": "988", "poison_control": "1-844-764-7669"},
    {"country": "Australia", "ambulance": "000", "police": "000", "fire": "000", "emergency_medical": "000", "mental_health_helpline": "13 11 14 (Lifeline)", "poison_control": "13 11 26"},
    {"country": "Germany", "ambulance": "112", "police": "110", "fire": "112", "emergency_medical": "112", "mental_health_helpline": "0800 111 0 111 (Telefonseelsorge)", "poison_control": "030 19240"},
    {"country": "Japan", "ambulance": "119", "police": "110", "fire": "119", "emergency_medical": "119", "mental_health_helpline": "0570-783-556 (TELL)", "poison_control": "03-5285-8181"},
    {"country": "Brazil", "ambulance": "192", "police": "190", "fire": "193", "emergency_medical": "192", "mental_health_helpline": "188 (CVV)", "poison_control": "0800-722-6001"},
    {"country": "Nigeria", "ambulance": "112", "police": "112", "fire": "112", "emergency_medical": "112", "mental_health_helpline": "08009120000 (Mentally Aware)", "poison_control": "01-7944929"},
    {"country": "South Africa", "ambulance": "10177", "police": "10111", "fire": "10177", "emergency_medical": "10177", "mental_health_helpline": "0800-567-567 (SADAG)", "poison_control": "0861-555-777"},
]
