"""
Local, curated knowledge base for diseases and common medicines.
This is the offline fallback / first line of the chatbot (fast, reliable,
no network dependency) and is what powers the Disease Profiles section.
Live medicine search (any drug name) is handled separately by openfda_client.py.
"""

# Common drug abbreviations, slang, and brand aliases → resolved name
DRUG_ALIASES = {
    "ctz": "cetirizine",
    "avil": "pheniramine",
    "crocin": "paracetamol",
    "dolo": "paracetamol",
    "tylenol": "paracetamol",
    "calpol": "paracetamol",
    "advil": "ibuprofen",
    "motrin": "ibuprofen",
    "brufen": "ibuprofen",
    "combiflam": "ibuprofen + paracetamol",
    "zyrtec": "cetirizine",
    "cetrine": "cetirizine",
    "alerid": "cetirizine",
    "allegra": "fexofenadine",
    "benadryl": "diphenhydramine",
    "phenergan": "promethazine",
    "volini": "diclofenac",
    "voveran": "diclofenac",
    "diclo": "diclofenac",
    "gelusil": "antacid",
    "pan": "pantoprazole",
    "pantop": "pantoprazole",
    "omez": "omeprazole",
    "omeza": "omeprazole",
    "azee": "azithromycin",
    "zifi": "cifixime",
    "cif": "cifixime",
    "augmentin": "amoxicillin + clavulanate",
    "amox": "amoxicillin",
    "met": "metformin",
    "glycomet": "metformin",
    "glucophage": "metformin",
    "telma": "telmisartan",
    "amlo": "amlodipine",
    "amlodac": "amlodipine",
    "atorva": "atorvastatin",
    "rosuvas": "rosuvastatin",
    "clopitab": "clopidogrel",
    "ecosprin": "aspirin",
    "aspirin": "aspirin",
    "ecotrin": "aspirin",
    "sinarest": "paracetamol + phenylephrine + chlorpheniramine",
    "vicks": "dextromethorphan",
    "benedryl": "diphenhydramine",
    "dramamine": "dimenhydrinate",
    "avomine": "promethazine",
    "stugil": "ondansetron",
    "ondem": "ondansetron",
    "ondansetron": "ondansetron",
    "panadol": "paracetamol",
    "tylenol": "paracetamol",
    "febrectol": "paracetamol",
    "meftal": "mefenamic acid",
    "meftal-spas": "mefenamic acid + dicyclomine",
    "dicyclomine": "dicyclomine",
    "buscopan": "hyoscine butylbromide",
    "ranitidine": "ranitidine",
    "zantac": "ranitidine",
    "pantodac": "pantoprazole",
    "razo": "pantoprazole",
    "lanzol": "lansoprazole",
    "lans": "lansoprazole",
    "ventolin": "salbutamol",
    "asthalin": "salbutamol",
    "duolin": "ipratropium + salbutamol",
    "deriphyllin": "theophylline",
    "theo": "theophylline",
    "sinarest": "paracetamol + pseudoephedrine",
    "levocet": "levocetirizine",
    "lcet": "levocetirizine",
    "aloquin": "hydroxychloroquine",
    "hcqs": "hydroxychloroquine",
    "chloroquine": "chloroquine",
    "doxycycline": "doxycycline",
    "doxy": "doxycycline",
    "metro": "metronidazole",
    "metronidazole": "metronidazole",
    "flagyl": "metronidazole",
    "nidazol": "metronidazole",
    "taxim": "ceftriaxone",
    "cef": "ceftriaxone",
    "ceftriaxone": "ceftriaxone",
    "monocef": "ceftriaxone",
    "panacea": "paracetamol",
    "ibugesic": "ibuprofen",
    "nise": "nimesulide",
    "nimesulide": "nimesulide",
    "nicide": "nimesulide",
    "tramadol": "tramadol",
    "ultram": "tramadol",
    "ultracet": "tramadol + paracetamol",
    "codeine": "codeine",
    "cofidox": "codeine",
    "morphine": "morphine",
    "hydrocodone": "hydrocodone",
    "oxycodone": "oxycodone",
    "percocet": "oxycodone + acetaminophen",
    "vicodin": "hydrocodone + acetaminophen",
    "diabet": "diabetes",
    "bp": "hypertension",
    "sugar": "diabetes",
    "tension": "hypertension",
    "cholesterol": "hyperlipidemia",
    "thyroid": "hypothyroidism",
    "sugar tablets": "metformin",
    "bp tablet": "amlodipine",
    "sugar tablet": "metformin",
    "cholesterol tablet": "atorvastatin",
}

DISEASE_KNOWLEDGE = {
    "diabetes": {
        "category": "Endocrine",
        "symptoms": ["Frequent urination", "Excessive thirst", "Extreme hunger", "Unexplained weight loss", "Fatigue", "Blurred vision", "Slow-healing sores", "Tingling in hands/feet"],
        "causes": ["Genetics", "Obesity", "Lack of physical activity", "Insulin resistance", "Autoimmune condition (Type 1)", "Pancreatic damage"],
        "treatment": ["Metformin", "Insulin therapy", "Diet control", "Regular exercise", "Blood sugar monitoring", "SGLT2 inhibitors", "GLP-1 agonists"],
        "prevention": ["Healthy diet", "Regular exercise", "Maintain healthy weight", "Regular check-ups", "Limit sugar intake"],
        "complications": ["Heart disease", "Kidney damage (nephropathy)", "Nerve damage (neuropathy)", "Eye problems (retinopathy)", "Foot problems", "Stroke"],
        "emergency_signs": ["Very high blood sugar (>300mg/dL)", "Ketones in urine", "Fruity breath odor", "Confusion", "Severe dizziness", "Loss of consciousness"],
        "when_to_see_doctor": "If experiencing persistent thirst/urination, unexplained weight loss, or blood sugar readings consistently above target range."
    },
    "hypertension": {
        "category": "Cardiovascular",
        "symptoms": ["Often asymptomatic", "Headache", "Shortness of breath", "Nosebleeds", "Flushing", "Dizziness", "Chest pain (severe cases)"],
        "causes": ["High salt diet", "Obesity", "Genetics", "Chronic stress", "Lack of exercise", "Smoking", "Excess alcohol", "Kidney disease"],
        "treatment": ["ACE inhibitors", "Calcium channel blockers", "Diuretics", "Beta-blockers", "ARBs", "Lifestyle changes"],
        "prevention": ["Reduce salt intake", "Regular exercise", "Healthy weight", "Stress management", "Limit alcohol", "Quit smoking"],
        "complications": ["Heart attack", "Stroke", "Kidney failure", "Vision loss", "Vascular dementia", "Aneurysm"],
        "emergency_signs": ["BP above 180/120 (hypertensive crisis)", "Severe headache", "Sudden vision changes", "Numbness/weakness", "Speech difficulty", "Chest pain"],
        "when_to_see_doctor": "Get BP checked regularly even without symptoms — hypertension is often silent until complications arise."
    },
    "fever": {
        "category": "General/Infectious",
        "symptoms": ["High body temperature (>38°C)", "Chills", "Sweating", "Headache", "Muscle aches", "Loss of appetite", "Fatigue", "Dehydration"],
        "causes": ["Viral infection", "Bacterial infection", "Heat exhaustion", "Inflammatory conditions", "Medication side effects", "Vaccination response"],
        "treatment": ["Paracetamol", "Ibuprofen", "Rest", "Hydration", "Cold compress", "Light clothing"],
        "prevention": ["Vaccination", "Hand washing", "Avoid close contact with sick people", "Good hygiene"],
        "complications": ["Dehydration", "Febrile seizures (children)", "Underlying infection worsening"],
        "emergency_signs": ["Very high fever (above 40°C)", "Seizures", "Stiff neck", "Difficulty breathing", "Confusion", "Persistent vomiting", "Rash"],
        "when_to_see_doctor": "If fever exceeds 39.5°C, lasts more than 3 days, or is accompanied by severe symptoms."
    },
    "common cold": {
        "category": "Respiratory",
        "symptoms": ["Runny nose", "Sneezing", "Cough", "Sore throat", "Mild headache", "Low-grade fever", "Nasal congestion", "Watery eyes"],
        "causes": ["Rhinovirus", "Coronavirus (common cold strains)", "Cold weather exposure", "Weak immune system", "Close contact with infected person"],
        "treatment": ["Rest", "Hydration", "Antihistamines", "Decongestants", "Paracetamol for fever", "Throat lozenges", "Steam inhalation"],
        "prevention": ["Hand washing", "Avoid touching face", "Vitamin C", "Warm clothing", "Avoid crowded places", "Adequate sleep"],
        "complications": ["Sinus infection", "Ear infection", "Bronchitis (rare)"],
        "emergency_signs": ["High fever", "Difficulty breathing", "Wheezing", "Chest pain", "Severe headache", "Symptoms lasting >10 days"],
        "when_to_see_doctor": "If symptoms worsen after a week or are accompanied by high fever or breathing difficulty."
    },
    "influenza": {
        "category": "Respiratory",
        "symptoms": ["Sudden high fever", "Severe body aches", "Dry cough", "Extreme fatigue", "Headache", "Sore throat", "Chills"],
        "causes": ["Influenza A/B virus", "Seasonal transmission", "Close contact with infected individuals"],
        "treatment": ["Rest", "Fluids", "Antivirals (oseltamivir) if started early", "Paracetamol", "Symptomatic relief"],
        "prevention": ["Annual flu vaccine", "Hand hygiene", "Avoid crowded indoor spaces during flu season"],
        "complications": ["Pneumonia", "Bronchitis", "Worsening of chronic conditions", "Hospitalization in high-risk groups"],
        "emergency_signs": ["Difficulty breathing", "Persistent chest pain", "Severe dehydration", "Bluish lips/face", "Confusion"],
        "when_to_see_doctor": "High-risk individuals (elderly, pregnant, chronic illness) should seek care early; others if symptoms are severe or worsening."
    },
    "asthma": {
        "category": "Respiratory",
        "symptoms": ["Wheezing", "Shortness of breath", "Chest tightness", "Coughing (especially at night)", "Difficulty exercising"],
        "causes": ["Allergens (dust, pollen, pet dander)", "Genetics", "Air pollution", "Respiratory infections", "Cold air", "Exercise"],
        "treatment": ["Inhaled bronchodilators (Salbutamol)", "Inhaled corticosteroids", "Leukotriene modifiers", "Avoiding triggers"],
        "prevention": ["Identify and avoid triggers", "Use air purifiers", "Regular use of preventer inhalers", "Flu vaccination"],
        "complications": ["Severe asthma attacks", "Reduced lung function over time", "Sleep disturbance"],
        "emergency_signs": ["Severe breathlessness", "Inability to speak full sentences", "Bluish lips", "No relief from rescue inhaler"],
        "when_to_see_doctor": "If using rescue inhaler more than twice a week or experiencing nighttime symptoms regularly."
    },
    "migraine": {
        "category": "Neurological",
        "symptoms": ["Throbbing head pain (often one-sided)", "Nausea", "Vomiting", "Sensitivity to light and sound", "Visual aura", "Dizziness"],
        "causes": ["Genetics", "Hormonal changes", "Stress", "Certain foods/additives", "Sleep changes", "Sensory stimuli"],
        "treatment": ["Triptans", "NSAIDs", "Anti-nausea medication", "Preventive medications (beta-blockers, anticonvulsants)", "Rest in dark room"],
        "prevention": ["Identify and avoid triggers", "Regular sleep schedule", "Stress management", "Stay hydrated", "Limit caffeine"],
        "complications": ["Chronic migraine", "Medication overuse headache", "Status migrainosus"],
        "emergency_signs": ["Sudden 'worst-ever' headache", "Headache with fever and stiff neck", "Headache after head injury", "Weakness or vision loss"],
        "when_to_see_doctor": "If migraines are frequent, worsening, or not responding to standard treatment."
    },
    "headache": {
        "category": "Neurological",
        "symptoms": ["Head pain", "Sensitivity to light", "Nausea", "Difficulty concentrating", "Neck stiffness"],
        "causes": ["Stress", "Dehydration", "Eye strain", "Sinus issues", "Tension", "Poor posture", "Lack of sleep"],
        "treatment": ["Ibuprofen", "Paracetamol", "Rest", "Hydration", "Cold compress", "Dark quiet room"],
        "prevention": ["Stay hydrated", "Regular sleep", "Stress management", "Eye breaks from screens", "Good posture"],
        "complications": ["Chronic daily headache", "Medication overuse headache"],
        "emergency_signs": ["Sudden severe headache", "Headache with fever", "Headache with confusion", "Loss of consciousness", "Worst headache of life"],
        "when_to_see_doctor": "If headaches are frequent, severe, or accompanied by neurological symptoms."
    },
    "gastroenteritis": {
        "category": "Digestive",
        "symptoms": ["Diarrhea", "Vomiting", "Abdominal cramps", "Nausea", "Low-grade fever", "Dehydration"],
        "causes": ["Viral infection (norovirus, rotavirus)", "Bacterial infection (Salmonella, E. coli)", "Contaminated food/water", "Parasites"],
        "treatment": ["Oral rehydration solution", "Rest", "Bland diet (BRAT)", "Antiemetics if needed", "Probiotics"],
        "prevention": ["Hand washing", "Safe food handling", "Clean drinking water", "Proper food storage"],
        "complications": ["Severe dehydration", "Electrolyte imbalance", "Kidney injury (severe cases)"],
        "emergency_signs": ["Signs of severe dehydration", "Blood in stool/vomit", "High fever", "Persistent vomiting unable to keep fluids down"],
        "when_to_see_doctor": "If symptoms last more than 2-3 days, or there are signs of dehydration or blood in stool."
    },
    "gerd": {
        "category": "Digestive",
        "symptoms": ["Heartburn", "Acid regurgitation", "Chest discomfort", "Difficulty swallowing", "Chronic cough", "Bloating"],
        "causes": ["Weak lower esophageal sphincter", "Obesity", "Spicy/fatty food", "Smoking", "Pregnancy", "Hiatal hernia"],
        "treatment": ["Proton pump inhibitors (Omeprazole)", "H2 blockers", "Antacids", "Dietary changes", "Weight loss"],
        "prevention": ["Avoid trigger foods", "Eat smaller meals", "Don't lie down right after eating", "Maintain healthy weight"],
        "complications": ["Esophagitis", "Esophageal stricture", "Barrett's esophagus"],
        "emergency_signs": ["Severe chest pain", "Difficulty swallowing solids", "Vomiting blood", "Black stools"],
        "when_to_see_doctor": "If symptoms occur more than twice a week or over-the-counter remedies aren't helping."
    },
    "insomnia": {
        "category": "Sleep/Mental Health",
        "symptoms": ["Difficulty falling asleep", "Waking up during night", "Early morning awakening", "Daytime fatigue", "Irritability", "Poor concentration"],
        "causes": ["Stress", "Poor sleep habits", "Caffeine", "Alcohol", "Medical conditions", "Medications", "Anxiety/depression"],
        "treatment": ["Improved sleep hygiene", "Relaxation techniques", "Melatonin", "Cognitive behavioral therapy (CBT-I)", "Short-term sleep aids (doctor-guided)"],
        "prevention": ["Regular sleep schedule", "Avoid caffeine before bed", "Limit screen time", "Relaxing bedtime routine", "Comfortable sleep environment"],
        "complications": ["Chronic fatigue", "Worsened mental health", "Reduced immune function"],
        "emergency_signs": ["Severe anxiety", "Depression with hopelessness", "Suicidal thoughts"],
        "when_to_see_doctor": "If insomnia persists for more than a few weeks and affects daily functioning."
    },
    "anxiety disorder": {
        "category": "Mental Health",
        "symptoms": ["Excessive worry", "Restlessness", "Fatigue", "Difficulty concentrating", "Irritability", "Rapid heartbeat", "Muscle tension"],
        "causes": ["Genetics", "Brain chemistry", "Chronic stress", "Trauma", "Medical conditions", "Substance use"],
        "treatment": ["Cognitive behavioral therapy", "Exercise", "Deep breathing/relaxation", "Medications (SSRIs, SNRIs)", "Mindfulness practices"],
        "prevention": ["Regular exercise", "Stress management", "Healthy diet", "Social support", "Limit caffeine/alcohol"],
        "complications": ["Panic disorder", "Social isolation", "Substance misuse", "Depression"],
        "emergency_signs": ["Panic attacks with chest pain", "Shortness of breath", "Suicidal thoughts", "Inability to function"],
        "when_to_see_doctor": "If anxiety interferes significantly with daily life or relationships."
    },
    "depression": {
        "category": "Mental Health",
        "symptoms": ["Persistent sadness", "Loss of interest in activities", "Fatigue", "Sleep changes", "Appetite changes", "Difficulty concentrating", "Feelings of hopelessness", "Low self-worth"],
        "causes": ["Genetics", "Brain chemistry imbalance", "Trauma", "Chronic stress", "Medical conditions", "Major life events", "Social isolation"],
        "treatment": ["Psychotherapy (CBT, talk therapy)", "Exercise", "Social support", "Antidepressants (under medical supervision)", "Lifestyle changes"],
        "prevention": ["Healthy relationships", "Regular exercise", "Stress management", "Early professional help", "Adequate sleep"],
        "complications": ["Suicidal ideation", "Substance abuse", "Social withdrawal", "Physical health decline"],
        "emergency_signs": ["Suicidal thoughts or plans", "Self-harm", "Not eating for extended periods", "Severe withdrawal from others"],
        "when_to_see_doctor": "Please reach out to a mental health professional if persistent sadness or hopelessness lasts more than two weeks."
    },
    "urinary tract infection": {
        "category": "Urological",
        "symptoms": ["Burning sensation while urinating", "Frequent urge to urinate", "Cloudy urine", "Pelvic pain", "Strong-smelling urine", "Low-grade fever"],
        "causes": ["Bacterial infection (commonly E. coli)", "Poor hygiene", "Holding urine too long", "Sexual activity", "Catheter use"],
        "treatment": ["Antibiotics (Nitrofurantoin, Trimethoprim)", "Increased water intake", "Pain relief (Phenazopyridine)", "Cranberry products (supportive)"],
        "prevention": ["Stay hydrated", "Urinate after intercourse", "Proper hygiene", "Avoid holding urine"],
        "complications": ["Kidney infection (pyelonephritis)", "Recurrent UTIs", "Sepsis (rare, severe cases)"],
        "emergency_signs": ["High fever with chills", "Severe back/flank pain", "Blood in urine", "Confusion (especially elderly)"],
        "when_to_see_doctor": "At first signs of UTI symptoms, especially if fever or back pain develops."
    },
    "allergic rhinitis": {
        "category": "Allergic/Immune",
        "symptoms": ["Sneezing", "Runny/itchy nose", "Itchy watery eyes", "Nasal congestion", "Postnasal drip"],
        "causes": ["Pollen", "Dust mites", "Pet dander", "Mold", "Seasonal allergens"],
        "treatment": ["Antihistamines (Cetirizine, Loratadine)", "Nasal corticosteroid sprays", "Decongestants", "Allergen avoidance", "Immunotherapy"],
        "prevention": ["Avoid known allergens", "Use air purifiers", "Keep windows closed during high pollen", "Regular cleaning"],
        "complications": ["Sinusitis", "Sleep disruption", "Worsened asthma"],
        "emergency_signs": ["Difficulty breathing", "Swelling of face/throat (anaphylaxis)", "Severe wheezing"],
        "when_to_see_doctor": "If symptoms are persistent year-round or significantly affect quality of life."
    },
    "anemia": {
        "category": "Hematological",
        "symptoms": ["Fatigue", "Pale skin", "Shortness of breath", "Dizziness", "Cold hands/feet", "Rapid heartbeat", "Brittle nails"],
        "causes": ["Iron deficiency", "Vitamin B12/folate deficiency", "Chronic disease", "Blood loss", "Genetic conditions (thalassemia, sickle cell)"],
        "treatment": ["Iron supplements", "Vitamin B12/folate supplements", "Dietary changes", "Treating underlying cause", "Blood transfusion (severe cases)"],
        "prevention": ["Iron-rich diet", "Vitamin C with iron-rich meals", "Regular health screening", "Manage chronic conditions"],
        "complications": ["Heart problems", "Pregnancy complications", "Developmental delays (children)"],
        "emergency_signs": ["Severe shortness of breath", "Chest pain", "Fainting", "Very rapid heartbeat"],
        "when_to_see_doctor": "If experiencing persistent fatigue, pale skin, or breathlessness on minimal exertion."
    },
    "thyroid disorder (hypothyroidism)": {
        "category": "Endocrine",
        "symptoms": ["Fatigue", "Weight gain", "Cold intolerance", "Dry skin", "Hair loss", "Constipation", "Depression", "Muscle weakness"],
        "causes": ["Hashimoto's thyroiditis (autoimmune)", "Iodine deficiency", "Thyroid surgery/radiation", "Certain medications"],
        "treatment": ["Levothyroxine (thyroid hormone replacement)", "Regular thyroid function monitoring"],
        "prevention": ["Adequate iodine intake", "Regular screening if at risk", "Monitor during pregnancy"],
        "complications": ["Goiter", "Heart problems", "Myxedema (severe, rare)", "Infertility"],
        "emergency_signs": ["Severe lethargy", "Confusion", "Very low body temperature", "Slow heart rate with fainting"],
        "when_to_see_doctor": "If experiencing unexplained fatigue, weight changes, or cold intolerance — get thyroid levels checked."
    },
    "arthritis": {
        "category": "Musculoskeletal",
        "symptoms": ["Joint pain", "Stiffness (especially morning)", "Swelling", "Reduced range of motion", "Warmth around joint"],
        "causes": ["Age-related wear (osteoarthritis)", "Autoimmune response (rheumatoid arthritis)", "Genetics", "Joint injury", "Obesity"],
        "treatment": ["NSAIDs (Ibuprofen)", "Physical therapy", "DMARDs (for RA)", "Corticosteroid injections", "Weight management", "Joint replacement (severe cases)"],
        "prevention": ["Maintain healthy weight", "Regular low-impact exercise", "Protect joints during activity"],
        "complications": ["Joint deformity", "Reduced mobility", "Chronic pain"],
        "emergency_signs": ["Sudden severe joint swelling with fever (possible joint infection)", "Inability to move joint"],
        "when_to_see_doctor": "If joint pain persists beyond a few weeks or significantly limits daily activities."
    },
    "eczema": {
        "category": "Dermatological",
        "symptoms": ["Itchy skin", "Dry, red patches", "Cracked or scaly skin", "Small bumps that may ooze", "Skin thickening from scratching"],
        "causes": ["Genetics", "Dry skin", "Irritants (soaps, detergents)", "Allergens", "Stress", "Heat and sweat", "Immune system dysfunction"],
        "treatment": ["Moisturizers (emollients)", "Topical corticosteroids", "Antihistamines for itch relief", "Topical calcineurin inhibitors", "Avoiding triggers", "Wet wrap therapy"],
        "prevention": ["Regular moisturizing", "Avoid harsh soaps", "Wear soft cotton clothing", "Keep nails short", "Humidifier in dry environments"],
        "complications": ["Skin infections", "Sleep disruption", "Emotional distress", "Asthma (atopic march)"],
        "emergency_signs": ["Signs of skin infection (pus, fever)", "Widespread rash", "Fever with rash"],
        "when_to_see_doctor": "If OTC moisturizers and hydrocortisone don't control symptoms after 1-2 weeks."
    },
    "urticaria (hives)": {
        "category": "Dermatological/Allergic",
        "symptoms": ["Raised, red or skin-colored welts", "Intense itching", "Swelling (angioedema)", "Welts that move around the body"],
        "causes": ["Allergic reactions (food, medication, insect stings)", "Physical triggers (heat, cold, pressure)", "Infections", "Stress", "Autoimmune conditions"],
        "treatment": ["Antihistamines (Cetirizine, Loratadine)", "Avoiding known triggers", "Cold compresses", "Corticosteroids (severe cases)", "Omalizumab (chronic cases)"],
        "prevention": ["Identify and avoid triggers", "Keep a symptom diary", "Wear loose-fitting clothing"],
        "complications": ["Anaphylaxis (rare but dangerous)", "Chronic hives affecting quality of life"],
        "emergency_signs": ["Difficulty breathing", "Swelling of throat/tongue", "Dizziness or fainting", "Rapid pulse"],
        "when_to_see_doctor": "If hives last more than 6 weeks, recur frequently, or are accompanied by swelling of lips/throat."
    },
    "alzheimer's disease": {
        "category": "Neurological",
        "symptoms": ["Memory loss", "Confusion", "Difficulty with familiar tasks", "Misplacing things", "Poor judgment", "Withdrawal from social activities", "Mood and personality changes", "Difficulty finding words"],
        "causes": ["Age (most significant risk factor)", "Genetics (family history)", "Down syndrome", "Cardiovascular disease", "History of head trauma", "Low education level"],
        "treatment": ["Cholinesterase inhibitors (Donepezil, Rivastigmine, Galantamine)", "Memantine", "Lecanemab (newer anti-amyloid therapy)", "Supportive care and cognitive stimulation", "Managing behavioral symptoms"],
        "prevention": ["Regular physical exercise", "Mental stimulation", "Social engagement", "Heart-healthy diet", "Control blood pressure and diabetes", "Quality sleep"],
        "complications": ["Inability to perform daily activities", "Infections (pneumonia, UTIs)", "Falls and fractures", "Malnutrition", "Complete dependence on caregivers"],
        "emergency_signs": ["Sudden severe confusion", "Falls with head injury", "Inability to eat or drink", "Seizures", "Sudden personality change"],
        "when_to_see_doctor": "If memory problems or confusion are interfering with daily life. Early diagnosis allows for better planning and treatment."
    },
    "skin rash": {
        "category": "Dermatological",
        "symptoms": ["Red, irritated skin", "Itching", "Bumps or blisters", "Swelling", "Warmth at affected area"],
        "causes": ["Allergic reactions", "Infections (bacterial, viral, fungal)", "Autoimmune conditions", "Medication side effects", "Contact irritants", "Heat/sweat"],
        "treatment": ["Topical corticosteroids", "Antihistamines", "Antibiotics (if bacterial)", "Antifungals (if fungal)", "Moisturizers", "Avoiding triggers"],
        "prevention": ["Avoid known allergens", "Use hypoallergenic products", "Keep skin clean and moisturized", "Wear breathable fabrics"],
        "complications": ["Skin infection", "Scarring", "Post-inflammatory hyperpigmentation", "Chronic skin changes"],
        "emergency_signs": ["Rapidly spreading rash", "Rash with fever", "Rash with difficulty breathing", "Blistering or peeling skin"],
        "when_to_see_doctor": "If rash is widespread, painful, blistering, accompanied by fever, or doesn't improve with OTC treatment."
    },
}

# Maps common symptom phrases (lowercase) to candidate diseases above.
SYMPTOM_TO_DISEASE = {
    "frequent urination": ["diabetes", "urinary tract infection"],
    "excessive thirst": ["diabetes"],
    "weight loss": ["diabetes", "depression"],
    "weight gain": ["thyroid disorder (hypothyroidism)"],
    "fatigue": ["diabetes", "anxiety disorder", "depression", "common cold", "fever", "anemia", "thyroid disorder (hypothyroidism)"],
    "blurred vision": ["diabetes"],
    "headache": ["hypertension", "fever", "common cold", "headache", "migraine"],
    "shortness of breath": ["hypertension", "fever", "asthma", "anemia"],
    "high blood pressure": ["hypertension"],
    "fever": ["fever", "common cold", "influenza", "urinary tract infection"],
    "chills": ["fever", "influenza"],
    "runny nose": ["common cold", "allergic rhinitis"],
    "sneezing": ["common cold", "allergic rhinitis"],
    "cough": ["common cold", "influenza", "asthma"],
    "sore throat": ["common cold", "influenza"],
    "nausea": ["fever", "headache", "migraine", "gastroenteritis", "gerd"],
    "vomiting": ["gastroenteritis", "migraine"],
    "diarrhea": ["gastroenteritis"],
    "stress": ["headache", "anxiety disorder", "insomnia"],
    "sleep": ["insomnia"],
    "worry": ["anxiety disorder"],
    "sadness": ["depression"],
    "hopelessness": ["depression"],
    "restlessness": ["anxiety disorder"],
    "panic": ["anxiety disorder"],
    "irritability": ["anxiety disorder", "insomnia", "thyroid disorder (hypothyroidism)"],
    "wheezing": ["asthma"],
    "chest tightness": ["asthma"],
    "heartburn": ["gerd"],
    "burning urination": ["urinary tract infection"],
    "joint pain": ["arthritis"],
    "stiffness": ["arthritis"],
    "pale skin": ["anemia"],
    "cold intolerance": ["thyroid disorder (hypothyroidism)"],
    "hair loss": ["thyroid disorder (hypothyroidism)"],
    "itchy eyes": ["allergic rhinitis"],
    "itchy skin": ["eczema", "urticaria (hives)", "allergic rhinitis"],
    "itching": ["eczema", "urticaria (hives)", "allergic rhinitis", "skin rash"],
    "skin rash": ["eczema", "urticaria (hives)", "skin rash", "allergic rhinitis"],
    "hives": ["urticaria (hives)"],
    "red welts": ["urticaria (hives)"],
    "raised bumps": ["urticaria (hives)", "eczema"],
    "dry skin": ["eczema", "thyroid disorder (hypothyroidism)"],
    "memory loss": ["alzheimer's disease", "depression", "thyroid disorder (hypothyroidism)"],
    "confusion": ["alzheimer's disease", "diabetes", "hypertension", "urinary tract infection"],
    "forgetfulness": ["alzheimer's disease", "depression", "anxiety disorder"],
    "difficulty concentrating": ["depression", "anxiety disorder", "insomnia", "anemia"],
    "mood changes": ["alzheimer's disease", "depression", "anxiety disorder", "thyroid disorder (hypothyroidism)"],
    "personality changes": ["alzheimer's disease", "depression"],
    "muscle pain": ["arthritis", "migraine", "influenza"],
    "body ache": ["influenza", "fever", "common cold"],
    "back pain": ["arthritis", "urinary tract infection"],
    "abdominal pain": ["gastroenteritis", "gerd"],
    "bloating": ["gerd", "gastroenteritis"],
    "constipation": ["thyroid disorder (hypothyroidism)", "depression"],
    "rash": ["eczema", "urticaria (hives)", "skin rash"],
    "dry eyes": ["allergic rhinitis", "thyroid disorder (hypothyroidism)"],
    "nasal congestion": ["common cold", "allergic rhinitis"],
    "postnasal drip": ["allergic rhinitis", "common cold"],
    "sinus pain": ["common cold", "allergic rhinitis"],
    "ear pain": ["common cold", "influenza"],
    "toothache": ["common cold"],
    "eye pain": ["migraine"],
    "sensitivity to light": ["migraine"],
    "throbbing head pain": ["migraine"],
    "swollen glands": ["common cold", "influenza"],
    "night sweats": ["fever", "influenza"],
    "dizziness": ["hypertension", "anemia", "migraine"],
    "loss of appetite": ["depression", "gastroenteritis", "fever"],
    "muscle weakness": ["thyroid disorder (hypothyroidism)", "anemia"],
    "tingling": ["diabetes", "anemia"],
    "numbness": ["diabetes", "hypertension"],
    "cold hands": ["anemia", "thyroid disorder (hypothyroidism)"],
    "brittle nails": ["anemia", "thyroid disorder (hypothyroidism)"],
    "swelling": ["arthritis", "urinary tract infection"],
    "swollen joints": ["arthritis"],
    "knee pain": ["arthritis"],
    "neck pain": ["arthritis", "migraine"],
    "burning sensation": ["urinary tract infection", "diabetes"],
    "frequent headaches": ["hypertension", "migraine"],
    "difficulty breathing": ["asthma", "anemia", "hypertension"],
    "swollen throat": ["allergic rhinitis"],
    "chronic cough": ["asthma", "gerd", "common cold"],
    "acid reflux": ["gerd"],
    "indigestion": ["gerd", "gastroenteritis"],
    "brain fog": ["anxiety disorder", "depression", "insomnia", "thyroid disorder (hypothyroidism)"],
    "tremor": ["anxiety disorder", "thyroid disorder (hypothyroidism)"],
    "palpitations": ["anxiety disorder", "thyroid disorder (hypothyroidism)", "anemia"],
    "loss of interest": ["depression"],
    "social withdrawal": ["depression", "alzheimer's disease"],
    "difficulty finding words": ["alzheimer's disease"],
    "difficulty with familiar tasks": ["alzheimer's disease"],
    "misplacing things": ["alzheimer's disease"],
    "poor judgment": ["alzheimer's disease"],
}

# Curated offline medicines — used as instant fallback if openFDA is
# unreachable, and to guarantee good answers for the most common drugs.
LOCAL_MEDICINES = [
    {
        "id": "paracetamol", "name": "Paracetamol", "brand": "Crocin, Calpol, Dolo, Tylenol, Panadol, Febrectol",
        "category": "Analgesic, Antipyretic",
        "uses": ["Fever", "Headache", "Mild to moderate pain", "Body ache", "Toothache", "Menstrual pain"],
        "symptoms_treated": ["Fever", "Headache", "Body ache", "Toothache", "Menstrual cramps"],
        "side_effects": {"common": ["Nausea", "Stomach upset"], "serious": ["Liver damage (overdose)", "Allergic reactions"]},
        "dosage": {"adult": "500-1000mg every 6-8 hours. Max 4g/day", "child": "15mg/kg every 6-8 hours", "elderly": "Same as adult, monitor liver function"},
        "how_to_use": "Take with or after food. Do not exceed recommended dose.",
        "precautions": ["Avoid if you have liver disease", "Do not drink alcohol", "Do not take with other paracetamol-containing products"],
        "interactions": ["Blood thinners (warfarin) - increased bleeding risk", "Alcohol - increased liver damage risk"],
        "pregnancy": "Generally considered safe when used as directed. Consult doctor.",
        "breastfeeding": "Safe in normal doses, consult doctor.", "source": "Curated reference"
    },
    {
        "id": "amoxicillin", "name": "Amoxicillin", "brand": "Amoxil, Mox, Novamox, Trimox, Amox",
        "category": "Antibiotic, Penicillin-class",
        "uses": ["Bacterial infections", "Throat infection", "Sinusitis", "Urinary tract infection", "Ear infection"],
        "symptoms_treated": ["Sore throat", "Fever with infection", "Ear pain", "Sinus pain"],
        "side_effects": {"common": ["Diarrhea", "Nausea", "Vomiting", "Skin rash"], "serious": ["Severe allergic reactions", "C. difficile infection"]},
        "dosage": {"adult": "250-500mg every 8 hours", "child": "20-45mg/kg/day in divided doses", "elderly": "Dose adjustment for kidney problems"},
        "how_to_use": "Complete full course even if symptoms improve. Take with food.",
        "precautions": ["Inform doctor if allergic to penicillin", "Inform doctor if you have kidney disease"],
        "interactions": ["Oral contraceptives - may reduce effectiveness", "Allopurinol - increased rash risk"],
        "pregnancy": "Generally considered safe during pregnancy. Consult doctor.",
        "breastfeeding": "Safe during breastfeeding.", "source": "Curated reference"
    },
    {
        "id": "ibuprofen", "name": "Ibuprofen", "brand": "Brufen, Advil, Motrin, Combiflam, Ibugesic",
        "category": "NSAID, Anti-inflammatory",
        "uses": ["Pain", "Inflammation", "Fever", "Arthritis", "Menstrual cramps", "Muscle pain"],
        "symptoms_treated": ["Joint pain", "Muscle pain", "Menstrual cramps", "Fever", "Inflammation"],
        "side_effects": {"common": ["Stomach upset", "Heartburn", "Nausea", "Dizziness"], "serious": ["Stomach ulcer/bleeding", "Kidney problems"]},
        "dosage": {"adult": "200-400mg every 6-8 hours. Max 1.2g/day OTC", "child": "5-10mg/kg every 6-8 hours", "elderly": "Use lowest effective dose"},
        "how_to_use": "Always take after meals. Use lowest effective dose for shortest duration.",
        "precautions": ["Avoid in stomach ulcers", "Avoid in kidney disease", "Avoid in heart problems", "Avoid in late pregnancy"],
        "interactions": ["Blood thinners - increased bleeding risk", "Aspirin - reduced cardioprotective effect"],
        "pregnancy": "Avoid in third trimester; use with caution earlier.",
        "breastfeeding": "Generally compatible in low doses, consult doctor.", "source": "Curated reference"
    },
    {
        "id": "cetirizine", "name": "Cetirizine", "brand": "Zyrtec, Cetrine, Alerid, CTZ",
        "category": "Antihistamine",
        "uses": ["Allergies", "Hay fever", "Allergic rhinitis", "Urticaria (hives)", "Itching", "Skin rash", "Eczema"],
        "symptoms_treated": ["Sneezing", "Runny nose", "Itchy eyes", "Itchy skin", "Skin rash", "Hives", "Itching"],
        "side_effects": {"common": ["Drowsiness", "Dry mouth", "Fatigue"], "serious": ["Severe allergic reactions (rare)"]},
        "dosage": {"adult": "10mg once daily", "child": "2.5-5mg once daily (6-12 years)", "elderly": "Start with 5mg once daily"},
        "how_to_use": "Can be taken with or without food. Take at the same time each day.",
        "precautions": ["Avoid driving if drowsy", "Inform doctor if you have kidney disease", "Avoid alcohol"],
        "interactions": ["Alcohol - increased drowsiness", "Sedatives - increased drowsiness"],
        "pregnancy": "Use only if clearly needed, consult doctor.",
        "breastfeeding": "Small amounts pass into breast milk, use with caution.", "source": "Curated reference"
    },
    {
        "id": "pheniramine", "name": "Pheniramine", "brand": "Avil, Aller-AF, Demazin, Phenadoz",
        "category": "Antihistamine",
        "uses": ["Allergies", "Hay fever", "Urticaria (hives)", "Itching", "Skin rash", "Common cold symptoms", "Motion sickness"],
        "symptoms_treated": ["Sneezing", "Runny nose", "Itchy eyes", "Itchy skin", "Skin rash", "Hives", "Itching", "Nasal congestion"],
        "side_effects": {"common": ["Drowsiness", "Dry mouth", "Dizziness", "Blurred vision"], "serious": ["Severe allergic reactions (rare)", "Urinary retention (rare)"]},
        "dosage": {"adult": "25mg every 6-8 hours (max 150mg/day)", "child": "12.5mg every 6-8 hours (6-12 years)", "elderly": "Start with lower dose, 12.5-25mg"},
        "how_to_use": "Take with food to reduce stomach upset. Avoid driving or operating machinery.",
        "precautions": ["Avoid driving if drowsy", "Avoid alcohol", "Caution in glaucoma, prostate enlargement", "Not recommended for elderly at high doses"],
        "interactions": ["Alcohol - increased drowsiness", "MAO inhibitors - avoid combination", "Sedatives - increased drowsiness"],
        "pregnancy": "Use only if clearly needed. Consult doctor.",
        "breastfeeding": "Small amounts pass into breast milk. Use with caution.", "source": "Curated reference"
    },
    {
        "id": "loratadine", "name": "Loratadine", "brand": "Claritin, Allegra-L, Lorid",
        "category": "Antihistamine (Non-drowsy)",
        "uses": ["Allergies", "Hay fever", "Urticaria (hives)", "Itching", "Skin rash", "Runny nose"],
        "symptoms_treated": ["Sneezing", "Runny nose", "Itchy eyes", "Itchy skin", "Hives", "Itching"],
        "side_effects": {"common": ["Headache", "Drowsiness (rare)", "Dry mouth"], "serious": ["Severe allergic reactions (very rare)"]},
        "dosage": {"adult": "10mg once daily", "child": "5mg once daily (2-12 years)", "elderly": "10mg once daily (no adjustment needed)"},
        "how_to_use": "Can be taken with or without food. Does not typically cause drowsiness.",
        "precautions": ["Generally well-tolerated", "Adjust dose for severe liver disease"],
        "interactions": ["Erythromycin - slight increase in levels", "Cimetidine - slight increase in levels"],
        "pregnancy": "Considered safe in pregnancy. Consult doctor.",
        "breastfeeding": "Secreted in breast milk; use with caution.", "source": "Curated reference"
    },
    {
        "id": "metformin", "name": "Metformin", "brand": "Glycomet, Glucophage, Metmin",
        "category": "Antidiabetic (Biguanide)",
        "uses": ["Type 2 diabetes", "Polycystic ovary syndrome", "Prediabetes"],
        "symptoms_treated": ["High blood sugar", "Excessive thirst", "Frequent urination", "Fatigue"],
        "side_effects": {"common": ["Nausea", "Diarrhea", "Stomach upset"], "serious": ["Lactic acidosis (rare)", "Vitamin B12 deficiency (long-term)"]},
        "dosage": {"adult": "500mg twice daily, titrated up; or 850mg once daily", "child": "Children 10-16: 500-1000mg twice daily", "elderly": "Start with lower dose"},
        "how_to_use": "Take with meals to reduce stomach side effects.",
        "precautions": ["Inform doctor if you have kidney disease", "Inform doctor if you have liver disease", "Stop before contrast imaging procedures"],
        "interactions": ["Alcohol - increased lactic acidosis risk", "Contrast media - increased lactic acidosis risk"],
        "pregnancy": "Sometimes used under medical supervision; consult doctor.",
        "breastfeeding": "Generally considered compatible with breastfeeding.", "source": "Curated reference"
    },
    {
        "id": "omeprazole", "name": "Omeprazole", "brand": "Prilosec, Omez, Ocid",
        "category": "Proton Pump Inhibitor (PPI)",
        "uses": ["GERD", "Acid reflux", "Stomach ulcers", "H. pylori treatment (combo therapy)"],
        "symptoms_treated": ["Heartburn", "Acid regurgitation", "Stomach pain"],
        "side_effects": {"common": ["Headache", "Nausea", "Abdominal pain", "Diarrhea"], "serious": ["Increased fracture risk (long-term)", "Low magnesium (long-term)"]},
        "dosage": {"adult": "20-40mg once daily before breakfast", "child": "Weight-based, consult pediatrician", "elderly": "Same as adult, monitor long-term use"},
        "how_to_use": "Take 30-60 minutes before a meal, preferably breakfast. Swallow whole, don't crush.",
        "precautions": ["Long-term use needs medical supervision", "May mask symptoms of stomach cancer"],
        "interactions": ["Clopidogrel - reduced effectiveness", "Certain antifungals - altered absorption"],
        "pregnancy": "Generally considered safe, consult doctor.",
        "breastfeeding": "Limited data; consult doctor.", "source": "Curated reference"
    },
    {
        "id": "salbutamol", "name": "Salbutamol", "brand": "Ventolin, Asthalin, ProAir",
        "category": "Bronchodilator (SABA)",
        "uses": ["Asthma", "COPD", "Exercise-induced bronchospasm"],
        "symptoms_treated": ["Wheezing", "Shortness of breath", "Chest tightness"],
        "side_effects": {"common": ["Tremor", "Rapid heartbeat", "Headache", "Nervousness"], "serious": ["Severe allergic reaction (rare)", "Paradoxical bronchospasm (rare)"]},
        "dosage": {"adult": "1-2 puffs (100-200mcg) as needed, max 8 puffs/day", "child": "1-2 puffs as needed under guidance", "elderly": "Same as adult"},
        "how_to_use": "Use inhaler as directed; shake well before use; rinse mouth after use.",
        "precautions": ["Overuse may indicate poor asthma control — see a doctor", "Caution with heart conditions"],
        "interactions": ["Beta-blockers - reduced effectiveness", "Diuretics - low potassium risk"],
        "pregnancy": "Generally considered safe when needed, consult doctor.",
        "breastfeeding": "Generally considered compatible.", "source": "Curated reference"
    },
    {
        "id": "levothyroxine", "name": "Levothyroxine", "brand": "Synthroid, Eltroxin, Thyronorm",
        "category": "Thyroid Hormone Replacement",
        "uses": ["Hypothyroidism", "Goiter (some cases)", "Thyroid cancer (post-surgery)"],
        "symptoms_treated": ["Fatigue", "Weight gain", "Cold intolerance", "Hair loss"],
        "side_effects": {"common": ["Headache (overdose)", "Insomnia (overdose)"], "serious": ["Heart palpitations (overdose)", "Bone density loss (long-term overdose)"]},
        "dosage": {"adult": "Typically 25-200mcg once daily, individualized via blood tests", "child": "Weight-based, pediatric endocrinologist guidance", "elderly": "Start low, go slow"},
        "how_to_use": "Take on empty stomach, 30-60 minutes before breakfast, with water only.",
        "precautions": ["Avoid taking with calcium/iron supplements (separate by 4 hours)", "Regular thyroid function monitoring required"],
        "interactions": ["Calcium/iron supplements - reduced absorption", "Warfarin - altered effect"],
        "pregnancy": "Often dose-adjusted during pregnancy under medical care.",
        "breastfeeding": "Generally considered safe and necessary if needed.", "source": "Curated reference"
    },
    {
        "id": "diclofenac", "name": "Diclofenac", "brand": "Volini, Voveran, Dicloran, Cataflam",
        "category": "NSAID, Anti-inflammatory",
        "uses": ["Pain", "Inflammation", "Arthritis", "Muscle pain", "Sprains", "Dental pain", "Migraine"],
        "symptoms_treated": ["Joint pain", "Muscle pain", "Back pain", "Swelling", "Inflammation"],
        "side_effects": {"common": ["Stomach upset", "Nausea", "Dizziness", "Skin rash at application site"], "serious": ["Stomach ulcer/bleeding", "Kidney problems", "Cardiovascular events (long-term oral use)"]},
        "dosage": {"adult": "25-50mg 2-3 times daily (oral); gel applied 3-4 times daily", "child": "0.5-2mg/kg/day in divided doses", "elderly": "Use lowest effective dose for shortest duration"},
        "how_to_use": "Take with food if oral. Apply gel thinly to affected area. Do not use on broken skin.",
        "precautions": ["Avoid in stomach ulcers", "Avoid in kidney disease", "Avoid in heart problems", "Avoid in late pregnancy", "Do not combine with other NSAIDs"],
        "interactions": ["Blood thinners - increased bleeding risk", "Lithium - increased levels", "Methotrexate - increased toxicity"],
        "pregnancy": "Avoid especially in third trimester. Consult doctor.",
        "breastfeeding": "Avoid topical use near breasts; oral use not recommended.", "source": "Curated reference"
    },
    {
        "id": "pantoprazole", "name": "Pantoprazole", "brand": "Pantop, Pan, Pantodac, Razo, PPI-40",
        "category": "Proton Pump Inhibitor (PPI)",
        "uses": ["GERD", "Acid reflux", "Zollinger-Ellison syndrome", "Stress ulcer prevention", "H. pylori eradication (combo)"],
        "symptoms_treated": ["Heartburn", "Acid regurgitation", "Stomach pain", "Bloating"],
        "side_effects": {"common": ["Headache", "Nausea", "Abdominal pain", "Diarrhea", "Flatulence"], "serious": ["Bone fractures (long-term)", "Vitamin B12 deficiency (long-term)", "Low magnesium (long-term)"]},
        "dosage": {"adult": "40mg once daily before breakfast (can increase to 80mg)", "child": "Weight-based, consult pediatrician", "elderly": "20-40mg once daily"},
        "how_to_use": "Take 30-60 minutes before a meal. Swallow whole, do not crush or chew.",
        "precautions": ["Long-term use needs medical supervision", "May mask gastric cancer symptoms", "Not for immediate heartburn relief"],
        "interactions": ["Methotrexate - increased levels", "Clopidogrel - reduced effectiveness", "Atazanavir - avoid combination"],
        "pregnancy": "Use only if clearly needed. Consult doctor.",
        "breastfeeding": "Limited data; consult doctor.", "source": "Curated reference"
    },
    {
        "id": "azithromycin", "name": "Azithromycin", "brand": "Azee, Azithral, Zithromax, Zmax",
        "category": "Antibiotic, Macrolide",
        "uses": ["Bacterial infections", "Throat infection", "Respiratory infections", "Skin infections", "Ear infections", "Sexually transmitted infections"],
        "symptoms_treated": ["Sore throat", "Fever with infection", "Cough with infection", "Ear pain", "Skin infection"],
        "side_effects": {"common": ["Diarrhea", "Nausea", "Stomach pain", "Headache"], "serious": ["Severe allergic reactions", "Heart rhythm problems (rare)", "Liver problems (rare)"]},
        "dosage": {"adult": "500mg day 1, then 250mg daily for 4 days (Z-pack); or 500mg once weekly for 3 weeks", "child": "10mg/kg day 1, then 5mg/kg daily for 4 days", "elderly": "Same as adult, monitor heart rhythm"},
        "how_to_use": "Can be taken with or without food. Complete the full course as prescribed.",
        "precautions": ["Inform doctor if you have liver or heart disease", "Avoid in severe kidney disease", "Report irregular heartbeat"],
        "interactions": ["Antacids - reduce absorption", "Blood thinners (warfarin) - may increase effect", "Digoxin - increased levels"],
        "pregnancy": "Generally considered safe. Consult doctor.",
        "breastfeeding": "Small amounts in breast milk; use with caution.", "source": "Curated reference"
    },
    {
        "id": "nimesulide", "name": "Nimesulide", "brand": "Nise, Nisolide, Nicide, Nimulid",
        "category": "NSAID, Anti-inflammatory",
        "uses": ["Pain", "Inflammation", "Fever", "Dental pain", "Musculoskeletal pain", "Osteoarthritis"],
        "symptoms_treated": ["Joint pain", "Muscle pain", "Back pain", "Toothache", "Fever", "Inflammation"],
        "side_effects": {"common": ["Nausea", "Stomach upset", "Diarrhea", "Dizziness"], "serious": ["Liver damage (rare)", "Stomach ulcer/bleeding", "Kidney problems"]},
        "dosage": {"adult": "100mg twice daily after meals (max 200mg/day)", "child": "5mg/kg twice daily (not recommended under 12 years in some countries)", "elderly": "Use lowest effective dose"},
        "how_to_use": "Take after food. Use for shortest duration necessary. Max 15 days without medical advice.",
        "precautions": ["Avoid in liver disease", "Avoid in kidney disease", "Avoid in heart problems", "Not recommended in children under 12 in many countries", "Short-term use only"],
        "interactions": ["Blood thinners - increased bleeding risk", "Lithium - increased levels", "Diuretics - reduced effect"],
        "pregnancy": "Contraindicated in third trimester. Consult doctor.",
        "breastfeeding": "Not recommended during breastfeeding.", "source": "Curated reference"
    },
    {
        "id": "metronidazole", "name": "Metronidazole", "brand": "Flagyl, Metrogyl, Nidazol, Metrozole",
        "category": "Antibiotic, Antiprotozoal",
        "uses": ["Bacterial infections", "Amoebiasis", "Giardiasis", "H. pylori infection", "Dental infections", "Pelvic inflammatory disease", "Trichomoniasis"],
        "symptoms_treated": ["Diarrhea", "Abdominal pain", "Nausea", "Vomiting", "Fever with infection"],
        "side_effects": {"common": ["Nausea", "Metallic taste", "Loss of appetite", "Diarrhea"], "serious": ["Seizures (high doses)", "Peripheral neuropathy (prolonged use)", "Severe allergic reactions"]},
        "dosage": {"adult": "400-800mg 2-3 times daily (depending on infection)", "child": "7.5mg/kg every 8 hours", "elderly": "Adjust for severe liver disease"},
        "how_to_use": "Take with food. Do not drink alcohol during and for 48 hours after treatment.",
        "precautions": ["Do not consume alcohol (severe reaction: nausea, vomiting, flushing)", "Avoid prolonged use", "Report numbness or tingling"],
        "interactions": ["Alcohol - disulfiram-like reaction (severe)", "Warfarin - increased effect", "Lithium - increased levels"],
        "pregnancy": "Use only if clearly needed, especially in first trimester. Consult doctor.",
        "breastfeeding": "Small amounts in breast milk; consult doctor.", "source": "Curated reference"
    },
]

EMERGENCY_CONTACTS = [
    {"country": "India", "ambulance": "102", "police": "100", "fire": "101", "emergency_medical": "108", "mental_health_helpline": "9152987821 (AASRA)", "poison_control": "1066"},
    {"country": "USA", "ambulance": "911", "police": "911", "fire": "911", "emergency_medical": "911", "mental_health_helpline": "988 (Suicide & Crisis Lifeline)", "poison_control": "1-800-222-1222"},
    {"country": "UK", "ambulance": "999", "police": "999", "fire": "999", "emergency_medical": "999", "mental_health_helpline": "116123 (Samaritans)", "poison_control": "111 (NHS)"},
    {"country": "Canada", "ambulance": "911", "police": "911", "fire": "911", "emergency_medical": "911", "mental_health_helpline": "988", "poison_control": "1-844-764-7669"},
    {"country": "Australia", "ambulance": "000", "police": "000", "fire": "000", "emergency_medical": "000", "mental_health_helpline": "13 11 14 (Lifeline)", "poison_control": "13 11 26"},
]
